### ISSUE TITLE
pos_payment_change for France

### ISSUE THREAD

**Issue by LESTRAT21** [OCA/pos#1004]
I put this module for a French Retail (B2C) client. Very useful, it 's definitely an easier way to change payment in pos.

Just a question about the constrain which is present to check the value of Payment Change Policy. "If the module l10n_fr_certification is installed and if the current company has an inalterable accounting, it will not be possible to select the value 'Update Payments'". 

My client has "l10n_fr_pos_cert" but not  "l10n_fr_certification". I think it could be appropriate that the constrain checks whether one of these 2 modules is installed to prevent the "Update Payments" option to be chosen.

**Comment by legalsylvain** [comment]
Hi @LESTRAT21, #1096 could fix the problem. could you take a look ?

**Comment by LESTRAT21** [comment]
Hi 
the only module required is :[ l10n_fr_pos_cert,
](l10n_fr_pos_cert,)
