### ISSUE TITLE
OCA/pos: Your 16.0 branch isn't protected

### ISSUE THREAD

**Issue by rafaelbn** [OCA/pos#1007]
Hello @sbidoul 

The 16.0 branch in POS is unprotected. I can press button "protect" but it ask me for options.

This is the first time I see this in a OCA Branch, do you know the reason or how to solve it?

Thank you!
Regards

**Comment by rafaelbn** [comment]
Ping @legalsylvain

**Comment by legalsylvain** [comment]
Hi @rafaelbn. Thanks for the question. Could you investigate at the OCA level, asking in some maintainer repo ? If something has to be done, it should be done for the 200 OCA repos.
This warning is related to a new github configuration that appeared some months ago. I played with it in my grap repos, but I finally have to unprotect all my branches. Dont remember why exactly maybe something was wrong with the bot....

Closing. Please reopen if you find OCA recommandations.

**Comment by rafaelbn** [comment]
@legalsylvain this situation is only for POS and only for 16 versions.

This doesn't happen in other repo or branches through OCA

![imagen](https://github.com/OCA/pos/assets/8736623/321cf3f2-4f72-4097-9bee-2c02a80ee6b6)


So the thing should be done, it is only for this one... for POS not for all! 😄

**Comment by legalsylvain** [comment]
> @legalsylvain this situation is only for POS and only for 16 versions.
> This doesn't happen in other repo or branches through OCA

No. This doesn't happen **FOR YOU** in other repo or branches through OCA  ;-)

- you're admin of OCA/pos (you see settings tabs).
- You're not admin of OCA/sale-workflow (tab is hidden).

The warning is displayed only to admin people. (and on the default branch).

Check : I see a warning on that repo https://github.com/akretion/pywebdriver/ do you ?

regards

**Comment by rafaelbn** [comment]
Thank you! Understand! 😄 🙏🏼
