### ISSUE TITLE
[8.0] In Variant select popup Variant price are correct but in pos orderline it is using template price

### ISSUE THREAD

**Issue by krupesh-weboffice** [OCA/pos#101]
When I select product variant from the Template in pop-up it is displaying correct variant price but when product variant selected from pop-up in pos orderline it is taking template price bug need to fix.

@StefanRijnhart 
@antespi 
@pablocm-aserti 
@AdilHoumadi 
@JavierIniesta 
@pablocm-aserti

**Comment by llacroix** [comment]
Problem already fixed in pos_pricelist apparently.

**Comment by llacroix** [comment]
https://github.com/OCA/pos/pull/103
