### ISSUE TITLE
POS Pricelist Issue

### ISSUE THREAD

**Issue by teddywudh** [OCA/pos#102]
I installed the POS Pricelist module but when I try to create a session I got the following error message.

Unable to get property 'Product Price' of undefined or null reference

TypeError: Unable to get property 'Product Price' of undefined or null reference at initialize (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:4407:513) at Backbone.Model (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:2530:1283) at child (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:2572:441) at child (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:2572:441) at add_products (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:4396:213) at Anonymous function (http://tomywu.dyndns.info:8069/web/js/web.assets_common/65c3bd9:1085:584) at loaded (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:4162:3447) at Anonymous function (http://tomywu.dyndns.info:8069/web/js/web.assets_backend/7279cdf:4166:1029) at Anonymous function (http://tomywu.dyndns.info:8069/web/js/web.assets_common/65c3bd9:249:672) at fire (http://tomywu.dyndns.info:8069/web/js/web.assets_common/65c3bd9:243:278

Please help.

Teddy

**Comment by pedrobaeza** [comment]
Restart server, refresh browser and try again.

**Comment by teddywudh** [comment]
I restarted the server and refresh the browser. But received the same error message.

**Comment by pedrobaeza** [comment]
No clue then, because the module is working correctly. Try to reproduce on runbot. Maybe you have a non OCA module that screws up everything.

**Comment by alfieqashwa** [comment]
I can't install pos_pricelist in Odoo 9.0 too

log error : http://pastebin.com/e0JXMqLv

**Comment by legalsylvain** [comment]
pos pricelist module has not been ported for Odoo 9.0. that's why installable is set to False in the manifest. You can try to fix the problem and propose a solution for the community. 

thanks !
