### ISSUE TITLE
[16.0] pos_default_partner default partner should be visible in pos

### ISSUE THREAD

**Issue by andrel-exo** [OCA/pos#1020]
Hello,

I encountered an issue while utilizing the pos_default_partner module. Specifically, when attempting to create an order with an invoice, I received a warning message stating, "You need to select the customer before you can invoice or ship an order."

To provide better context, I have attached a screenshot of the warning message for reference:

![Screenshot from 2023-06-30 12-03-20](https://github.com/OCA/pos/assets/58446356/9741de16-e30b-4160-b1ad-f98d0c71c653)

In my opinion this should not happen as it has already been introduced earlier in the settings.

At the moment the module only introduces the default customer at the end of each order, which in my opinion can lead to some consistency errors. Thus, the module should also fill in the "customer" field within the PoS to avoid logic problems.

Thank you for your attention to this matter.

**Comment by legalsylvain** [comment]
Hi. this is a know limitation of the module.
see : https://github.com/OCA/pos/tree/16.0/pos_default_partner#known-issues--roadmap

Feel free to make a PR to make the feature also working in the PoS.
