### ISSUE TITLE
After refund of 1 qty, POS qty display increased by 2 qty

### ISSUE THREAD

**Issue by arjungitub** [OCA/pos#1039]
## Module
The name of the module that has a bug.
pos_stock_available_online
stock_available

## Describe the bug
When we are refunding 1 qty on the POS machine, qty of product is increased by 2. Please check this error.

## To Reproduce
I have tried on odoo16 only.

1. Sell a product in POS
2. Refund it.
3. Then check the qty displayed on POS

**Expected behavior**
Exact qty should be added after refund

**Comment by chienandalu** [comment]
@GabbasovDinar @francesco-ooops Maybe you're interested in checking this

**Comment by ivs-cetmix** [comment]
Hi @arjungitub , thank you for reporting! Will check this

**Comment by francesco-ooops** [comment]
@chienandalu @isserver1 I need to ask for confirmation to @GSLabIt who analyzed the issue internally a few months ago, but as far as I remember the issue was related to standard odoo pos return/refund feature (this info has to be verified)
