### ISSUE TITLE
[NEW] Payment.term in pos

### ISSUE THREAD

**Issue by mileo** [OCA/pos#104]
Hi, Our team is developing a new module module to extend pos adding payment.term

![pos_payment_terms](https://cloud.githubusercontent.com/assets/1975978/15377851/24b97c3e-1d35-11e6-8f2d-0f8db3c46323.png)

![captura de tela de 2016-05-14 08 36 27](https://cloud.githubusercontent.com/assets/1975978/15377877/4f5029f2-1d35-11e6-95bf-76abf9a637ff.png)

Tomorrow we will work on the adaptation of the accounting entries and soon we will do PR.

We appreciate any suggestions.

Thanks in advance

**Comment by rafaelbn** [comment]
Hi @mileo , I close this issue has the PR is done in : https://github.com/OCA/pos/pull/106
