### ISSUE TITLE
Error when trying to install [pos_order_reorder] on 15.0

### ISSUE THREAD

**Issue by thsdrouot** [OCA/pos#1059]
## Module
![image_2023-09-29_122135478](https://github.com/OCA/pos/assets/8808163/e90000e6-45b3-4bbe-9bb5-9c60947ea8ac)
[pos_order_reorder]

## Describe the bug
Get this error when installing : 
`KeyError: 'Field pos_config_id referenced in related field definition res.config.settings.pos_allow_reorder does not exist.'`

## To Reproduce
**Affected versions**: 15.0

1. Update modules list from backend in developper mode
2. Try to install the module 
3. You get the server error

**Expected behavior**
An simple installation of the module.

**Additional context**
Try on dev db and preproduction db. Get the same problem. Seems to lack a field in the model.

**Comment by legalsylvain** [comment]
Hi. pos_order_reorder is not an OCA module in V15 release. 

https://github.com/OCA/pos/tree/15.0
