### ISSUE TITLE
pos_stock_available_online

### ISSUE THREAD

**Issue by okelekemike** [OCA/pos#1060]
The model does not subtract live quantity on current sale.
## Module
The name of the module that has a bug.
pos_stock_available_online
## Describe the bug
When you make a film on the current opened POS section the quantity will still remain the same as when loaded. Only after  you close the session and then open again will all the quantity be updated with the normal values of the item sold.
## To Reproduce
**Affected versions**:

1. Open a new. session.
2. Make a seal of an item.
3. Check the quantity. It will remain the same.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by quentinDupont** [comment]
Hello !

It seems that stock is impacted only after the session being closed.
So, that's not really an issue about this module but rather a feature request ?

**Comment by flotho** [comment]
Hi @quentinDupont , it depends, you could enable the validation of the picking at each order, so the issue still relevant

**Comment by quentinDupont** [comment]
> Hi @quentinDupont , it depends, you could enable the validation of the picking at each order, so the issue still relevant

thanks i didn't know !
