### ISSUE TITLE
[16] pos_partner_firstname Can't create a contact

### ISSUE THREAD

**Issue by CLEBORGNEAPIK** [OCA/pos#1097]
## Module
pos_partner_firstname

## Describe the bug
Since the Odoo update (V16.0.2023.11.11), you can't creat a contact from a POS, the firstname and lastname wasn't save.

## To Reproduce
V16.0.2023.11.11

1. From a POS
2. Select a customer
3.Creat One
4. Write the firstname and lastname
5. Save

**Expected behavior**
Wan't creat a customer

**Comment by DorianMAG** [comment]
Hi @CLEBORGNEAPIK 
Have you find a solution?
Regards

**Comment by CLEBORGNEAPIK** [comment]
Hi @DorianMAG 
No, unfortunately I don't have the skills, I hope somebody can help me

**Comment by DorianMAG** [comment]
I start a code debug,
i will hope find a solution

**Comment by DorianMAG** [comment]
I found the beginning of a solution,
I hope make a first patch next monday.
Regards

**Comment by CLEBORGNEAPIK** [comment]
Hi @DorianMAG,
Well done, I can't wait to try this :)

**Comment by DorianMAG** [comment]
@CLEBORGNEAPIK 
Hi,
You can find my proposition to solved our problem here
https://github.com/OCA/pos/pull/1122
You can try in runboat
Regards

**Comment by CLEBORGNEAPIK** [comment]
@DorianMAG 
Well done, I've check and approve your work.
Thank's a lot

**Comment by DorianMAG** [comment]
A problem with 16.0 branch prevent to merge FIX, but you can use this branch for the moment.
Regards

**Comment by DorianMAG** [comment]
@CLEBORGNEAPIK 
The fix was merged in the main 16 branch
Probably close this issue,
Best regards

**Comment by CLEBORGNEAPIK** [comment]
@DorianMAG 
Thank's a lot, that's great !
