### ISSUE TITLE
pos_order_to_sale_order Fiscal Position applied at Header but not at OrderLines

### ISSUE THREAD

**Issue by xmorejon** [OCA/pos#1107]
## Module
pos_order_to_sale_order
"name": "PoS Order To Sale Order",
"version": "16.0.1.0.7",

## Describe the bug
Some customers have a Fiscal Position ("Recargo de Equivalencia") which should result on a +5.2% taxes on top of the Spanish VAT(21%).

Fiscal Positions is correctly set into the Sales Order/Other Info/Fiscal Position Field, but the Order Lines do not get automatically the 5.2% tax.

If Sales Order is invoiced directly, the Invoice will be wrong and will not reflect its Fiscal Position. 
I need to compute again the taxes manually prior to invoice it, to have it right.

## To Reproduce

1. Set into Point Of Sale configuration the Flag "Flexible Taxes" and add "Recargo de Equivalencia" in the "Allowed" ones:
<img width="479" alt="image" src="https://github.com/OCA/pos/assets/106985973/f064bf0b-97ad-4f93-a56b-6a25da6f84a1">

3. Generate a Sales Order. (As the Selected customer has a predefined "Fiscal Position", the POS is applying it already. That is Correct:
<img width="684" alt="image" src="https://github.com/OCA/pos/assets/106985973/31d7e5d7-e15f-4f02-a9b3-1131907014f1">

4. Sales Order has inherited the Fiscal Positions accordingly (correct):

<img width="948" alt="image" src="https://github.com/OCA/pos/assets/106985973/b69621a5-e36c-4acf-933b-e52be6d752fd">

5. Sales Order lines only have the 21% VAT but not the additional 5.2% corresponding to the Fiscal Position:
<img width="905" alt="image" src="https://github.com/OCA/pos/assets/106985973/291a7bf9-851d-4c4a-a28a-4daabcbd9cd8">

**Expected behavior**
Sales Order lines should have included the Fiscal Position condition:
<img width="904" alt="image" src="https://github.com/OCA/pos/assets/106985973/c1bd3801-c2fa-455d-89a7-a7ba658da795">

I am able to get those lines, if running the Method: action_update_taxes (Pressing "Update Taxes)
<img width="908" alt="image" src="https://github.com/OCA/pos/assets/106985973/2d06b474-e031-44b6-9757-664c189b43e8">

## About Me **
Xavier M from Barcelona
Administrator of Odoo for small family business. 
Years of experience in different programming languages, but learning Odoo since 4 months.
Running Odoo 16.0 Community version in own Virtual Machine (Ubuntu 22LTS, NGINX)

Not sure if this is a BUG or a missing configuration.
Any Comment or Workaround is welcome! (I.e. automatically force a re-compute Taxes prior to generate the Invoice. ¿Is such an automated trigger posible?)

T H A N K    Y O U!

**Comment by legalsylvain** [comment]
Hi. @xmorejon. As far as I understand, the taxes of the sale order lines, are the taxes on the pos order lines.
See : https://github.com/OCA/pos/blob/16.0/pos_order_to_sale_order/models/sale_order_line.py#L19

Are the pos order line correctly set ? 

thanks !

**Comment by xmorejon** [comment]
Hi,

The POS Order Line are not correctly set:
- Product Price=4,5€
- VAT (21%)= 0,945€
- Recarco Equivalencia (5,2%) = 0,234€
- Total taxes should be: 1,18€

At Product Info / line Level it is not displaying the 0,234€ in the POS Order Line:

<img width="788" alt="image" src="https://github.com/OCA/pos/assets/106985973/18648a13-bfe4-49e1-a865-db39b84816f4">

But on the Total it is correctly displayed:

<img width="476" alt="image" src="https://github.com/OCA/pos/assets/106985973/ce19aa1a-059c-4c22-bb98-3b1f81fec1d9">

Also if instead of generating the Sales Order, we do the Payment on the POS, the receipt will be correctly built:

<img width="284" alt="image" src="https://github.com/OCA/pos/assets/106985973/793bd645-28a2-42a9-b36e-b051b1e30a3e">

**Could it be that the Point of Sale does a recomputing of the taxes in a later stage, so while preparing Sales Order Lines from the POS Order Lines this Fiscal Position is wrong?**
https://github.com/OCA/pos/blob/16.0/pos_order_to_sale_order/models/sale_order_line.py#L19 

Thank you so much for looking into it!

**Comment by legalsylvain** [comment]
Well. Could add a screenshot of the pos order taxes in the back-office ?

**Comment by xmorejon** [comment]
Apologies not sure if I follow you:
- When I do a regular payment in the POS (instead of generating the Sales Order with "pos_order_to_sale_order" module) there is indeed a POS Order in the back-office:

<img width="954" alt="image" src="https://github.com/OCA/pos/assets/106985973/c2dd957d-efb6-4b0b-a695-d55291ed042f">

This one corresponds to the receipt of the screenshot Order 00172-001-001. Note that the Taxes are CORRECT.

- But when we generate a Sales order from the POS, there is NO "POS Order" so I cannot make a screenshot:

Sales Order screenshot:
<img width="932" alt="image" src="https://github.com/OCA/pos/assets/106985973/562c8cbc-3c1e-4e3a-93d1-99bf7a36f859">

No available POS Order: Order 00167-001-0001
<img width="951" alt="image" src="https://github.com/OCA/pos/assets/106985973/94a02427-d523-4900-8b47-64880de3f7c9">

But corresponding Sales Order in the back-office do miss the Fiscal Position items:

<img width="952" alt="image" src="https://github.com/OCA/pos/assets/106985973/c668de0f-4b08-411a-b0a9-a63cb12fffeb">

Should I look somewhere else?
Merci Sylvain!

**Comment by xmorejon** [comment]
Hi again!

Forcing a recompute of Taxes, did the trick and seems to fix the issue! :)

<img width="589" alt="image" src="https://github.com/OCA/pos/assets/106985973/77a1c520-5c88-4c8f-9f06-a10e4a874536">

And now the Sales Order has the correct Fiscal Position included:

<img width="956" alt="image" src="https://github.com/OCA/pos/assets/106985973/696680d5-d0d1-4cf2-ae30-103d1ddefe85">

As mentioned, I am pretty new to ODOO, and not sure if this way of fixing the issue is correct.
Therefore, I would wait for feedback and not suggest this pull request.

Thank you,

Xavier Morejon

**Comment by legalsylvain** [comment]
could you add a ``print(order_data)`` here : https://github.com/OCA/pos/blob/16.0/pos_order_to_sale_order/models/sale_order.py#L13 ? 
and put her the result.
thanks !

**Comment by xmorejon** [comment]
Hi,

Here you go. (Order with 2 lines):

{'name': 'Order 00188-001-0001', 'amount_paid': 0, 'amount_total': 11.36, 'amount_tax': 2.36, 'amount_return': 0, 'lines': [[0, 0, {'qty': 1, 'price_unit': 4.5, 'price_subtotal': 4.5, 'price_subtotal_incl': 5.68, 'discount': 0, 'product_id': 62, 'tax_ids': [[6, False, [1]]], 'id': 1, 'pack_lot_ids': [], 'description': '', 'full_product_name': 'B-0001', 'price_extra': 0, 'price_manually_set': False, 'price_automatically_set': False}], [0, 0, {'qty': 1, 'price_unit': 4.5, 'price_subtotal': 4.5, 'price_subtotal_incl': 5.68, 'discount': 0, 'product_id': 78, 'tax_ids': [[6, False, [1]]], 'id': 2, 'pack_lot_ids': [], 'description': '', 'full_product_name': 'BC-0002', 'price_extra': 0, 'price_manually_set': False, 'price_automatically_set': False}]], 'statement_ids': [], 'pos_session_id': 190, 'pricelist_id': 3, 'partner_id': 11157, 'user_id': 2, 'uid': '00188-001-0001', 'sequence_number': 1, 'creation_date': '2023-12-10T08:50:06.942Z', 'fiscal_position_id': 6, 'server_id': False, 'to_invoice': False, 'to_ship': False, 'is_tipped': False, 'tip_amount': 0, 'access_token': '3eb2f19d-8a81-4299-a0ff-e41ee1dce4df'}

<img width="628" alt="image" src="https://github.com/OCA/pos/assets/106985973/b2c0af1f-6b2e-4b04-8739-a9b1a37a408a">

So the Subtotal is right ->  'price_subtotal_incl': 5.68
But there is only one of the TaxID's (corresponding to the 21%) -> 'tax_ids': [[6, False, [1]]]

<img width="929" alt="image" src="https://github.com/OCA/pos/assets/106985973/66a3cefc-1c9f-4cbf-bfbd-568365f3ff2f">


Thank you.
Xavier

**Comment by legalsylvain** [comment]
Hi. At first glance, i think the problem is not in pos order to sale order module. The module just use export to JSON function that looks to return bad résult

https://github.com/OCA/pos/blob/16.0/pos_order_to_sale_order/static/src/js/CreateOrderPopup.js#L49

Investigation should be done over there.

Thanks !

**Comment by xmorejon** [comment]
Thank you Sylvain!
I believe you are right. As the issue looks to be out of this module, I will close the reported issue.

Will look further into:

<img width="415" alt="image" src="https://github.com/OCA/pos/assets/106985973/c40375cf-8202-48d6-9bc0-e009c1e66e42">

But might also apply the "dirty" fix of recomputing the taxes in alternate version of the module. I really need the Fiscal positions to give expected outcome!

Thank you very much. Great job!
Xavier
