### ISSUE TITLE
dos not work with localization

### ISSUE THREAD

**Issue by Maram-Azezzz** [OCA/pos#1147]
module: pos_receipt_hide_price
version: 16.0

**Steps to reproduce**
- ...
- install the module while KSA localization is installed

**Current behavior**
does not hide price with localization installed
**Expected behavior**
hide price with localization installed

**Comment by legalsylvain** [comment]
hi; @Maram-Azezzz. Thanks for reporting. 
Could you precise the technical name of the modules (localization) installed ? 
Di you reproduced the bug on runboat ? 

thanks !

**Comment by Maram-Azezzz** [comment]
this is the technical name
l10n_sa_pos
I didn't test on runboat
