### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Khnaz35** [OCA/pos#1219]
Hi everyone how to use this repo? Is there any readme.md or any demo available for it ?

**Comment by pedrobaeza** [comment]
Please ask question in the forums. This issue tracker is for notifying issues / bugs in the code.

**Comment by Khnaz35** [comment]
Thanks for answer @pedrobaeza can you link the official forum url

**Comment by pedrobaeza** [comment]
You can use https://github.com/OCA/pos/discussions or https://www.odoo.com/forum
