### ISSUE TITLE
[8.0] pos_pricelist throws an error with python type tax

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/pos#125]
Hi,

Point of Sale is throwing an error when it finishes loading the products. It just says "No traceback available" but I've noticed that the error comes when i've got pos_pricelist installed plus a tax configured with Python Code with tax included in the price...

Can someone throw some light? There's no debug possible, no errors, no traceback of the error... The only thing I know is that both things can't work at the same time.

Thanks

**Comment by liebana** [comment]
What "round method" do you have in configuration - accounting? If you set the value "round by line", I think it works. But if you "round globally" it doesn't.

**Comment by aitorbouzas** [comment]
@liebana 

Just tried what you said, but it's not working. It doesn't work with round by line, neither with round globalyl.

**Comment by legalsylvain** [comment]
Hi @Softdil. 
Point of sale should not be used with product with tax type "python code". without pricelist, it doesn't work in fact. 
- Install on a fresh instance point of sale module.
- create a tax (python code)
- create a product and set the tax.

load the PoS and try to sell the product.
The message is the following : 
![image](https://user-images.githubusercontent.com/3407482/34633832-109250f2-f27f-11e7-9e52-38a2ad072e7e.png)

you should disable the check box "can be sold in PoS" for such products.

kind regards.
