### ISSUE TITLE
Previous order remains in POS after ticket is printed

### ISSUE THREAD

**Issue by imaralux** [OCA/pos#128]
module: pos_pricelist
version: 8.0

**Steps to reproduce**
1) Make a sale, pay and print ticket
2) When button "Next Order" becomes available, do not click it
3) Directly scan (with a barcode reader) a barcode

**Current behavior**
The POS goes back to sale screen with previous items on it with the new one added

**Expected behavior**
Without the module activated, the previous items are cleared and only the new one is on the ticket

**Comment by imaralux** [comment]
Issue comes from models.js, previous order is not destroyed when printed (found out by looking at point_of_sale module function) :

One must add the following lines at the beginning of function (around line 87):
        addProduct: function (product, options) {
            if(this._printed){
                this.destroy();
                return this.pos.get('selectedOrder').addProduct(product, options);
            }

**Comment by legalsylvain** [comment]
Hi. I just proposed a patch here. #236 could you test it ? 
regards.

**Comment by legalsylvain** [comment]
Fixed.
