### ISSUE TITLE
[9.0] pos_quick_logout not listed in addons/modules, unable to install

### ISSUE THREAD

**Issue by innowintay** [OCA/pos#133]
Environment: Windows 2012r2
Odoo Version: 9.0-20161116
Despite being listed in the marketplace, pos_quick_logout cannot be found or installed. It must be installed manually.

Steps to reproduce:
1. Login to Odoo and open Apps
2. Clear all search filters and search for pos_quick_logout. Module does not appear so unable to install.

**Comment by legalsylvain** [comment]
Hi. 
This is not a bug from this module. You have to click on "update module list" in your case, after having rebooted the odoo Server. this is the standard installation process.

kind regards.
