### ISSUE TITLE
[8.0] pos_default_empty_image does not reduce loading time (in products with no image)

### ISSUE THREAD

**Issue by JGarcia-Panach** [OCA/pos#134]
We have tried the loading time for point of sale with different amounts of products and these are the results:

Specs of the computer:
Virtual Private Server (provider OVH)
4 vCores
3,1 GHz
8 GB RAM

Results (pos_default_empty_image not installed)
![image](https://cloud.githubusercontent.com/assets/13234598/20982948/e7def462-bcba-11e6-982c-58314a88f814.png)

Results (pos_default_empty_image installed)
![image](https://cloud.githubusercontent.com/assets/13234598/20982976/0ecfe09a-bcbb-11e6-80b1-74ee48ed46cb.png)

As you can see, there is no difference.

@legalsylvain, @pedrobaeza, @rafaelbn,  here are the tests

Kind regards

**Comment by legalsylvain** [comment]
Thanks a lot for that tests, and that interesting durations !

CC : @hparfr are you using this module in production ?

Kind regards.

**Comment by hparfr** [comment]
@JGarcia-Panach Thanks for this work.

I didn't work on the project recently so I can't do any tests now. 
As far as I remember, in my setup it did accelerate the loading time in prod for all the pos (often with poor connection).

In my project, there was only few products with images (less than 10%), and other pos modules were installed.

@JGarcia-Panach : how many images requests are done when you load the pos? (as many as displayed or all products)

**Comment by legalsylvain** [comment]
Indeed, I now remember how odoo works.
images are not loaded at the beginning of the POS (as the other data), but when product are displayed. (so only the first 80 when the POS is loaded.
but after, when you do a request. (typing a char in the search box), or selecting a category, others requests will be done to the server.
So it's quite normal that this module do not reduce loading time, but yes save connection during all the use of the POS.

(you can check the server log when you use products search)

**Comment by cvinh** [comment]
`__init__.py` is empty !

**Comment by pedrobaeza** [comment]
Because this is done through JS

**Comment by cvinh** [comment]
https://github.com/OCA/pos/pull/153

**Comment by cvinh** [comment]
@pedrobaeza I was talking about the inheritance for product.template that added has_image boolean field. I did a PR

**Comment by pedrobaeza** [comment]
Fixed in #153
