### ISSUE TITLE
[8.0] pos_product_template - Numpad not working for payment screen

### ISSUE THREAD

**Issue by berpweb** [OCA/pos#146]
I have bought and tried this https://apps.openerp.com/apps/modules/8.0/pos_multi_currency/ it is working fine. 

But the issue is when I install the OCA's Product template (https://www.odoo.com/apps/modules/8.0/pos_product_template/) the Numpad is not working for the payment widget, so as the touch screen.

Any idea what could be the conflict? I am new JS and kindly point me the right direction here guys.

**Comment by legalsylvain** [comment]
Hi @berpweb. unfortunately, the module pos_multi_currency is closed source. so it will not be possible for OCA members to investigate and fix that bug.
Please contact your seller and ask him to investigate.
Alternatively, you could ask him to open the source and share it to OCA. So it will be possible to understand and try to fix your problem.
kind regards.
