### ISSUE TITLE
[RFC] pos_sale: Create sale.orders in POS

### ISSUE THREAD

**Issue by lasley** [OCA/pos#151]
This module will add an option into `pos.config` to create quotes, similar to the invoice option. It will constrain that both it and the invoice option are not selected, because they will not be compatible with each other.

Another option will be added to the `pos.config` to select the email template that is used for outbound quote emails.

If the quote option is enabled, the "Payment" button will be a "Complete" button instead. Clicking it will create a `sale.order` in `draft` status & move the `pos.order` to a TBD status. There is likely going to be some account balancing that would need to happen in order to make things even, which can probably be inspired by the invoice logic.

In a glue module `website_pos_sale`, we will also add a field the `pos.config` allowing for the selection of the website quote template to use for the sale generation.

Logic will then be added into the `pos.session` that will send the quotes via email to the respective customers, if the mail template is filled in the configuration.

Anyone know of existing modules or strategies we can base on?

**Comment by legalsylvain** [comment]
Hi @lasley, 
The RFC is for wich serie ?
In 8.0, did you checked this work https://github.com/OCA/pos/pull/35 ? 

kind regards.

**Comment by lasley** [comment]
Oops how could I forget the most important detail?! This is for v10.

Looks like this is what we need though, particularly the round trip being referenced in https://github.com/OCA/pos/pull/35#issuecomment-263929481. 

Thanks @legalsylvain - this is exactly what we needed!
