### ISSUE TITLE
[9.0] BUG pos_customer_required when pos has a restaurant flor

### ISSUE THREAD

**Issue by damendieta** [OCA/pos#159]
If the configuration is set to order the POS do not start.

Steps to reproduce:

- Install pos_customer_required.
- Set require_customer to order.
- Install pos_restaurant
- Add a floor and several tables.
- Start a new session.

The pos will not start as the module conflict.

- Remove the floor.

The pos will start as usual.

IMPORTANT: Until this gets fixed, use payment instead of order when dealing with restaurant floors.

**Comment by legalsylvain** [comment]
Fixed here : https://github.com/OCA/pos/pull/237
could you test ? 
regards.
