### ISSUE TITLE
[help wanted] implement hw_ZVT_payment_terminal / port from existing python implementation

### ISSUE THREAD

**Issue by w0pr** [OCA/pos#161]
I need to support payment terminals talking ZVT protocol over RS-232; the spec (latest attached below) is downloadable from [terminalhersteller.de](http://terminalhersteller.de/Downloads.aspx?Seite=Downloads)

I found ecrterm (https://github.com/mathiasfrey/ecrterm), an implementation of ZVT 700 interface (in python, no less) with LGPL licence , so the effort is reduced to porting it so it satifies the Odoo interface.

[PA00P016_04_en.pdf](https://github.com/OCA/pos/files/890257/PA00P016_04_en.pdf)
[PA00P015_13.07_en.pdf](https://github.com/OCA/pos/files/890256/PA00P015_13.07_en.pdf)

**Comment by citronpower** [comment]
Any solution found?

**Comment by w0pr** [comment]
> Any solution found?

No, abandoned project, no more need on my part for the time being

There is a project using same ecrterm base for TCP/IP transport using twisted, though; effort for interfacing Odoo should be about the same, if someone wants to give it a try.
[https://github.com/tuvit-ug/py3-ecrterm](https://github.com/tuvit-ug/py3-ecrterm)
