### ISSUE TITLE
Pos Order Load bug

### ISSUE THREAD

**Issue by dansputy** [OCA/pos#179]
Hello 

I just noticed this why testing pos order load on Odoo version 8. On the Pos Screen, if an order is placed by a customer and saved into the system, the order status remain new in the system making the order to be loaded despite it has been paid and receipt printed.

The behaviour is that if the order is created and saved, on paying for the order a new order record is created again which has status of paid leaving the original order to be new which is disallowing closing and posting of pos session.

Please could somebody provide help.

Thanks.

**Comment by legalsylvain** [comment]
Hi. No the objective of this module is to save pos order in a draft state. you could then mark the order as paid.
"It's not a bug, it's a feature" ;-)

kind regards.
