### ISSUE TITLE
[10.0] pos_remove_pos_category: Crashing Odoo Studio

### ISSUE THREAD

**Issue by gustavovalverde** [OCA/pos#180]
This module is crashing Odoo Studio even if this module is not installed. And is also happening with this same module in the oca/account-invoicing.

![image](https://cloud.githubusercontent.com/assets/16890942/26769574/060ca56a-497e-11e7-9c86-f148aa2521ed.png)

**Comment by simahawk** [comment]
note that the module has been removed from this repo due to a serious bug https://github.com/OCA/pos/issues/200

**Comment by pedrobaeza** [comment]
Closing this as the previous comment.
