### ISSUE TITLE
[10.0]hw_customer_display Conflict with hw_scale

### ISSUE THREAD

**Issue by flotho** [OCA/pos#184]
Hi,

I'm using the hw_customer_display with the bixolon recommended in the readme.
I've set it up and the test script is working.

yet I have 2 issues :
* Using the posBOX hardware status page make the device displaying strange codes indefinitely
* When using the POS, each time a new message is displayed on the device, the first character of each line is replaced by the letter "P" a few seconds after having displayed the correct values.

@alexis-via did you already saw this kind of issue?

Any help would be appreciated.

regards

**Comment by flotho** [comment]
Hi,
Working with hw_scale seems to use the same serial channel as the customer display.
So when both are passed in the options, some special characters are displayed on the bixolon.
removing the hw_scale form the load modules solved the problem for us.

@alexis-via , did you already faced this kind of issue ?

regards

**Comment by legalsylvain** [comment]
Hi @flotho. could you say me which scale you're using with hw_scale, and if it works correctly ? 

kind regards.

**Comment by flotho** [comment]
Hi @legalsylvain , actually, no balance is used but the POSBOX come with all the hw_* modules loaded at start.
So I deactivate the module and no more confilcts in serial is solving my issue.
regards

**Comment by legalsylvain** [comment]
Hi @flotho, thanks for your answer. If you try to use scale connection, please ping me, I'm looking for a stable system.
regards.

**Comment by cvinh** [comment]
It looks like we have the same issue with hw_telium_payment_terminal.
In the posbox (odoo's one) status page, we see a connected scale but we did not connect any scale. Payment terminal is seen as a scale (we have DB9-USB cable between the Verifone payment terminal and the posbox)

**Comment by flotho** [comment]
@invitu 
We suspecting a serial port conflict. https://github.com/odoo/odoo/blob/10.0/addons/hw_scale/controllers/main.py#L127 is the one used by scale and by default the customer_display seems to use the same serial port. Give a try by changing the port name in the conf file for the hw_discount

**Comment by legalsylvain** [comment]
Alternatively, you could : 
- install pywebdriver instead of posbox
- uninstall hw_scale from your posbox

Maybe just add a warning on the hw_telium_payment_terminal description could be suficient. (Well incompatibility with an unused module is not really a bug)

what do you think ?

**Comment by alexis-via** [comment]
I think we should remove hw_* modules from OCA/pos 9.0 and 10.0 branches. It will make things clear. POSbox image currently runs odoo v8, so hw_* modules should only be present on 8.0 branch. When posbox image will be migrated to v11, we will port those hw_* modules to v11.

**Comment by alexis-via** [comment]
Here are the corresponding PR for v9 and v10: https://github.com/OCA/pos/pull/230 and https://github.com/OCA/pos/pull/231

**Comment by cvinh** [comment]
@alexis-via @flotho @legalsylvain this issue is not solved : we still have the issue by using hw_scale and hw_customer_display
we have ttyUSB0 for the customer display and ttyACM0 for the scale
We have Mettler Ariva S setup as follow : 
3.1: 1 – USB Virtual COM ports (USB Ser/CDC)
3.6: 3 – 8217 Mettler-Toledo (WO)
Thanks for your feedback

**Comment by alexis-via** [comment]
@invitu  : in hw_customer_display, the device name /dev/ttyUSB0 can be configured in the Odoo server config file of the POSBox, cf this line of code: https://github.com/OCA/pos/blob/8.0/hw_customer_display/controllers/main.py#L48

**Comment by cvinh** [comment]
@alexis-via thanks for replying. We already configured the port in /home/pi/odoo/addons/point_of_sale/tools/posbox/configuration/odoo.conf : 

customer_display_device_name = /dev/ttyUSB0
customer_display_device_rate = 9600

**Comment by cvinh** [comment]
I think this is the issue : 
pi@raspberrypi:~ $ ls -l /dev/serial/by-path/
total 0
lrwxrwxrwx 1 root root 13 Jun 12  2017 platform-3f980000.usb-usb-0:1.2.2:1.0-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Jun 12  2017 platform-3f980000.usb-usb-0:1.2.4:1.0 -> ../../ttyACM0
According to https://github.com/odoo/odoo/blob/10.0/addons/hw_scale/controllers/main.py#L127
hw_scale scans the serial ports. I have to ack hw_scale in order to make it scan the right port
I give you the solution soon

**Comment by cvinh** [comment]
ok I dirty hacked hw_scale here https://github.com/odoo/odoo/blob/10.0/addons/hw_scale/controllers/main.py#L215

devices = ['platform-3f980000.usb-usb-0:1.2.4:1.0']

given by 
ls -l /dev/serial/by-path/
lrwxrwxrwx 1 root root 13 Jun 12  2017 platform-3f980000.usb-usb-0:1.2.4:1.0 -> ../../ttyACM0

It works but it's very dirty ...
