### ISSUE TITLE
[Imperfection] pos variant overload does not handle high variant counts properly

### ISSUE THREAD

**Issue by blaggacao** [OCA/pos#228]
High variant counts could have been excluded from the UI because
    of the general search limit. Furthermore, using primary variant flag
    strategy for display, a search can return awkward results when no primary
    variant is displayed, although we would have had a valid search hit.

**Comment by legalsylvain** [comment]
Hi @blaggacao. Thanks for reporting. please check before existing issue and PR, before creating a new one.

Current issue : 
https://github.com/OCA/pos/issues/64
https://github.com/OCA/pos/issues/108

pending fix to review : https://github.com/OCA/pos/pull/135

kind regards.

**Comment by blaggacao** [comment]
It's partly a duplicate, if you want you can keep it open for the `is_primary_variant` splicing issue...
