### ISSUE TITLE
More features for pos_access_right

### ISSUE THREAD

**Issue by yelizariev** [OCA/pos#232]
I recently subscribed to OCA/pos repository updates and found that there is a module [pos_access_right](https://github.com/OCA/pos/blob/9.0/pos_access_right/README.rst), which is very close to our module  [pos_disable_payment](https://github.com/it-projects-llc/pos-addons/blob/11.0/pos_disable_payment/README.rst)

Would be great to merge both modules to one in order to combine our efforts and don't maintain two parallel modules.

From my side, I consider to stop maintaining for ``pos_disable_payment`` in in next odoo release (12.0) and move disjoint features to  ``pos_access_right``. If someone else has a will to do it in earlier version, I am ready to help and review.

**Comment by yelizariev** [comment]
Common features:

```
    PoS - Negative Quantity: The cashier can sell negative quantity in Point Of Sale (ie, can return products);
    PoS - Discount: The cashier can set Discount in Point Of Sale;
    PoS - Change Unit Price: The cashier can change the unit price of a product in Point Of Sale;
    PoS - Delete Order: The cashier can not delete a full order;

```
Features only in pos_access_right:
* PoS - Many Orders: The cashier can many orders at the same time;

Features only in pos_disable_payment:
* disable payments
* disable create order line 
* disable remove order line

**Comment by pedrobaeza** [comment]
Thanks for the initiative. I'm not using that features right now, but I also can help in the review.

**Comment by legalsylvain** [comment]
Hi @yelizariev. I realized this module for a customer that doesn't t requires this pos_access_right in a new version of Odoo. But if you port this module or merge new feature, I'll review it. 
regards.

**Comment by blaggacao** [comment]
I'll put myself on the ping list...
I've developed a feature to limit not only per user, but also per `pos.config` for the case that the `pos.config` conveys such ordenance by legal circumstances (only certain machines might do payments)...

**Comment by GabbasovDinar** [comment]
I have an idea of improving `the pos_access_right` module. We can add new fields to `res.groups` (`pos_discount`, `pos_change_unit_price` and etc.). Each `pos.config` has `many2many` field to `res.groups` (one POS may have different access groups, for example, POS manager, POS Waiter, POS Cashier and etc). After loading the POS the user will have access rights that intersect with the rights from the `pos.config` and `res.groups` for the user. For example, the Admin belongs to POS-manager group, the Demo belongs to POS-user group, both these groups are specified in POS Config, then when changing the user in the POS, each user will have their own rights.

Cc: @yelizariev @pedrobaeza @blaggacao

**Comment by yelizariev** [comment]
cc @legalsylvain

**Comment by yelizariev** [comment]
The PR: https://github.com/OCA/pos/pull/302

**Comment by pedrobaeza** [comment]
Closing this as there's a PR.
