### ISSUE TITLE
[8.0] hw_customer_display conflict with hw_scale

### ISSUE THREAD

**Issue by cvinh** [OCA/pos#243]
We still have the issue by using hw_scale and hw_customer_display
we have ttyUSB0 for the customer display and ttyACM0 for the scale
We have Mettler Ariva S setup as follow :
3.1: 1 – USB Virtual COM ports (USB Ser/CDC)
3.6: 3 – 8217 Mettler-Toledo (WO)
Thanks for your feedback

The issue for v10 has been closed here https://github.com/OCA/pos/issues/184 because the hw_* modules are not available anymore for v9.0 here https://github.com/OCA/pos/pull/230 and v10.0 here https://github.com/OCA/pos/pull/231

**Comment by cvinh** [comment]
Dirty hack solution is given here https://github.com/OCA/pos/issues/184#issuecomment-363584258

**Comment by rousseldenis** [comment]
@cvinh Is this still relevant ?
