### ISSUE TITLE
odoo 10 pos_pircelist crashes with the last changes

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/pos#250]
With the last changes pos_pricelist makes this warning

2018-02-28 06:28:42,997 23040 WARNING ? odoo.addons.pos_pricelist.models.pos_config: Missing dependency

Before last changes worked fine.
The dependency problem is not documented

¿What is the dependency required not documented?

Now odoo is not available

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.18 (Ubuntu) Server at garganta.humanoide.es Port 443

**Comment by pedrobaeza** [comment]
pos_pricelist has just been merged, so there has not been other previous dependency. You must have something incorrect in your end or an incompatible module. Check README.

**Comment by pedrobaeza** [comment]
We have discovered a bug, but not the one you have mentioned: #251
