### ISSUE TITLE
POS Search Product by Serial NUMBER 

### ISSUE THREAD

**Issue by sah-anshu** [OCA/pos#258]
Hi

The POS Search shall be able to search with Product Serial NUMBER too. It will be very useful for Quick Product selection. 

![screen shot 2018-03-13 at 6 46 34 pm](https://user-images.githubusercontent.com/9985291/37344801-5d9cadce-26f1-11e8-814c-8a2856fa2e02.png)
![screen shot 2018-03-13 at 6 48 38 pm](https://user-images.githubusercontent.com/9985291/37344802-5ddbc70c-26f1-11e8-8a40-1d5318d616df.png)

Anshu S.

**Comment by chienandalu** [comment]
Well, lots aren't loaded on the POS start, so that's not currently possible.
