### ISSUE TITLE
Product Serial NUMBER Is not printed in POS Invoice.

### ISSUE THREAD

**Issue by sah-anshu** [OCA/pos#259]
Hi
I am not able to see that product serial number which i placed while placing order. DO i need to change any setting anywhere. 

![screen shot 2018-03-13 at 6 49 52 pm](https://user-images.githubusercontent.com/9985291/37344989-e2230340-26f1-11e8-8a7e-250fe8393635.png)

Anshu S.

**Comment by chienandalu** [comment]
Hi, @sah-anshu . It's not available in the ticket layout by default. You could extend the QWeb template, anyway.
