### ISSUE TITLE
field error at the time of install

### ISSUE THREAD

**Issue by reenajarali** [OCA/pos#272]
when i am trying to install module get Field `use_pricelist` does not exist error

**Comment by chienandalu** [comment]
@reenajarali You should state what module and Odoo version you are testing

**Comment by reenajarali** [comment]
pos_pricelist module getting from following url https://www.odoo.com/apps/modules/10.0/pos_pricelist/
in version 10

**Comment by chienandalu** [comment]
a full error trace would be useful as well

**Comment by pedrobaeza** [comment]
You are not restarting Odoo server. This is not a problem on the module.

**Comment by reenajarali** [comment]
i  restarted odoo server and then trying to install module but getting same error again and again.actually this issue with one another field as available_pricelist_ids,both fields are created in pos_config class.this fields used in xml .

**Comment by pedrobaeza** [comment]
Your module installation is not correct. On runbot is working correctly: http://3326014-10-0-15386f.runbot1.odoo-community.org/?db=3326014-10-0-15386f-all (admin/admin)
