### ISSUE TITLE
Manage Payments in Pos to Sale Order

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/pos#273]
Points of sale was extented to allow managing Pos to sale order workflow 
https://github.com/OCA/pos/pull/264
however payment of sale order is not managed in this module. 
So we propose to manage this by :
    1- extending the module to integrate to it the payment feature for sale order (solution used by Akretion in odoo 8.0 see https://github.com/akretion/pos/tree/8.0-fix-pos-account-bank-statement/pos_sale_order) 
    2-  Adding a new module for this feature. 
In this solution (1 or 2) we add payments on sale_order object (link to bank statement). 
    We create an user anonymous to allow to create order for not identified customer. 
    We put a new journal (Pos Sale ORDER) to separate regular invoices from pos anonymous invoices. 
    Accounting entry are handled by generating invoice. When we close pos session we generate grouped invoice for anonymous customer. And for each not invoiced order with identified customer we generate an invoice too.  Then we reconcile invoices with payments (linked on order).

Use case : 
A customer who pass to point of sale to take there products that are fractured at the end of month for the major part of sale orders. So actually if customer pay cash its order we must generate a pos order (to make payment). This is not good for the Follow Up and Statistics. If we add payments management on pos to sale order we can make all the process in sale order (cash payment  or late payment). When a company asks for customization of sale (by adding new fields on sale order or sale product with options  for example). It is easier to maintain this customization on an object (order of sale) than on 2 objects (sale and order of position).

ping @legalsylvain, @pedrobaeza, @hparfr, @chienandalu

**Comment by chienandalu** [comment]
@mourad-ehm The PR is still open. Why don't you debate this inside it?

**Comment by mourad-ehm** [comment]
Ok. i'll copy this issue on PR #264.
