### ISSUE TITLE
[pos_pricelist] Dropdown menu default menu error

### ISSUE THREAD

**Issue by Ark74** [OCA/pos#279]
**Issue:** 
As mentioned on title.

**Version:**
Tested on http://3331405-10-0-9ee349.runbot1.odoo-community.org (Odoo 10)

**Steps to reproduce:**
1. On POS Settings enable Pricelist (bottom of the page)
2. Try to change the **Default Pricelist** on the dropdown menu.
3. Error!
![dd-menu-pos](https://user-images.githubusercontent.com/7444518/42349804-14b86bec-806b-11e8-9e34-3353ade5fdf3.png)

**Comment by chienandalu** [comment]
@Ark74 Check here: https://github.com/OCA/pos/pull/280

**Comment by Ark74** [comment]
Thank you very much for looking into this. :pray: 
Please close this issue at will.
