### ISSUE TITLE
RFC - Retail Features for Odoo 13.0

### ISSUE THREAD

**Issue by legalsylvain** [OCA/pos#299]
Hi all, 

FYI, Odoo is working on verticalization for the serie 13.0. One of the verticalization is the "Retail" specially linked to the PoS.

A RFC is actually opened here : https://github.com/odoo/odoo/issues/28179

feel free to contribute.

regards

**Comment by rafaelbn** [comment]
But nothing for POS: https://github.com/odoo/odoo/issues/28179#issuecomment-433998208

**Comment by pedrobaeza** [comment]
Closing this as already noted.
