### ISSUE TITLE
pos_loyalty tests failing in CI

### ISSUE THREAD

**Issue by kirca** [OCA/pos#309]

**Comment by kirca** [comment]
https://github.com/OCA/pos/pull/308 eliminates possibility that it is related with timing. The output html in the logs after the step fails looks correct. Also I've tested successfully locally with same version of phantomjs (2.1.1).

**Comment by legalsylvain** [comment]
which version ?

**Comment by kirca** [comment]
11.0

**Comment by chienandalu** [comment]
I'd say it's failing on integration with Odoo's tests. Can you try to add (like here: https://github.com/OCA/pos/blob/11.0/pos_order_return/tests/test_pos_order_return.py#L9):

```python
@common.at_install(False)
@common.post_install(True)
```

**Comment by kirca** [comment]
Postponing tests till end doesn't affect the issue https://github.com/OCA/pos/pull/310

**Comment by kirca** [comment]
Maybe CI maintainer or someone who has access can check more closely if phantomjs tests fail in general or it is specific to this module.
