### ISSUE TITLE
11.0 -> 12.0 pos_order_mgmt splitting in several module

### ISSUE THREAD

**Issue by PierrickBrun** [OCA/pos#334]
I will soon migrate pos_order_mgmt from 11.0 to 12.0.

I think this is a good occasion to split it it in several modules:

- `pos_order_mgmt` to display old pos_orders
- `pos_order_mgmt_reprint` to reprint tickets
- `pos_order_mgmt_return` to return orders

That way we can only install what we need in our project.

Also that could be an occasion to integrate pos_order_return into pos_order_mgmt_return.

I'm not sure  that I will need `pos_order_mgmt_return` so I may not migrate that part

Any thoughts about this @chienandalu @legalsylvain ?

**Comment by chienandalu** [comment]
It can be interesting. There are some monolithic methods that should be considered to make them extensible, mainly this one: https://github.com/OCA/pos/blob/11.0/pos_order_mgmt/static/src/js/widgets.js#L184

Or this one: https://github.com/OCA/pos/blob/11.0/pos_order_mgmt/static/src/js/widgets.js#L262

**Comment by chienandalu** [comment]
I close this as the module migration is alredy on the go
