### ISSUE TITLE
POS with a cashier and multiple sellers

### ISSUE THREAD

**Issue by eabellom** [OCA/pos#338]
The POS ( odoo  #11) I see that is oriented to the seller and the cashier are the same person.
I want to know if it is possible to configure the
POS with a cashier and multiple sellers. Similar to how POS Restaurant works, that is, a person who enters an order in a POS transaction and another person in another session receives the payment. I have reviewed in ODOO 11 and some partners indicate them but I do not know if they are part of the Odoo base configuration or own module developments.
Thanks

**Comment by chienandalu** [comment]
There's nothing in the standard or OCA/pos that allows operate that way (sync between PoS), as the POS is designed to work in an isolated way: it loads the necessary data at the beginning of the session and it can request data to the DB, but it isn't designed to receive notification as in longpolling.

@GabbasovDinar You have something like this in your repos don't you?

**Comment by GabbasovDinar** [comment]
Hello @eabellom @chienandalu. Yes, we have the module for sync between several POSes (https://github.com/it-projects-llc/pos-addons/tree/12.0/pos_multi_session_restaurant). 
Also, you can set access to the functions for each user of the POS (for example, waiters cannot pay the order but for the cashier is allowed), you can install the additional module pos_access_right https://github.com/OCA/pos/pull/304

cc: @yelizariev

**Comment by eabellom** [comment]
Hi, thanks for your answer, this module is great, I only have one question, if I require it for POS Retail, not for a POS Restaurant, should I use pos_multi_session_restaurant ?, check the repository and look at this module .. https://github.com/it-projects-llc/pos-addons/tree/11.0/pos_multi_session ....this should be more suitable for POS Retail?

Thank you 

.... I take the opportunity to ask how I can collaborate in this project and in general in the OCA ... I have been working in this for about 8 months but I have experience in development

**Comment by GabbasovDinar** [comment]
@eabellom yes, you need to use the pos_mult_session module, but we have not tested the module with POS Retail

**Comment by yelizariev** [comment]
@GabbasovDinar POS Retail is just ``point_of_sale`` module.

@eabellom so, yes, just use pos_multi_session. You don't need pos_multi_session_restaurant

**Comment by yelizariev** [comment]
@eabellom if you are going to use ``pos_access_right`` module, please consider to send a review to #304

**Comment by eabellom** [comment]
@yelizariev OK, I see that it will affect version 12 ... so I assume that it will not affect the 11 ... is it like that?

**Comment by pedrobaeza** [comment]
Yes, but it is called "contribution" and "collaboration" :)

**Comment by GabbasovDinar** [comment]
> @GabbasovDinar POS Retail is just point_of_sale module.

@yelizariev I think we are talking about this module https://www.odoo.com/apps/modules/12.0/pos_retail/

**Comment by ncaccia** [comment]
Hi! @yelizariev does the pos_multi_session works with the OCA operation unit module? we are having some trouble with journal configuration. thanks!
