### ISSUE TITLE
[11.0] [pos_session_pay_invoice]

### ISSUE THREAD

**Issue by Joaco1980** [OCA/pos#355]
If you have another form of payment such as "Credit Card", when you try to collect an invoice and want to select another journal, return this error:

**Error: TypeError: 'float' object is unsubscriptable**

![Sin título](https://user-images.githubusercontent.com/14363121/57787526-d7dbf780-7735-11e9-8bf1-e1fa0b39301c.jpg)

**Comment by chienandalu** [comment]
Please, put the full traceback

**Comment by Joaco1980** [comment]
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:181
Traceback:
PY_getItem@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:181:82
evaluate@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:266:84
evaluate@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:265:119
evaluate@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:267:107
eval@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:272:292
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:380:140
forEach@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:12:566
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:69:531
eval_domains@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:379:269
_getDomain@[native code]
_search@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:1033:615
source@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:1026:65
_search@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1716:153
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1276:339
search@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1716:20
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1276:339
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1281:36
each@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:625:771
each@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:613:647
http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:1278:257
_onInputClick@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/583-eafa3a4/web.assets_backend.js:1038:741
dispatch@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:892:456
handle@http://3370017-11-0-0bc2cf.runbot1.odoo-community.org/web/content/577-81f765b/web.assets_common.js:865:178

**Comment by chienandalu** [comment]
Thanks @Joaco1980 What do you think? @etobella ?

**Comment by plche** [comment]
Dears,
Did you get to find a fix for this?
The module works correctly in 10.0, and this code was migrated from it, but actually (almost) nothing was changed in the migrated code, I guess that was because of using the migrations scripts...
Could you please suggest at least what could be causing such error (**Error: TypeError: 'float' object is unsubscriptable**)?

**Comment by jarroyomorales** [comment]
Hi @plche @Joaco1980 ! The error is in the domain of the journal_id in the xml definition. 

In file https://github.com/OCA/account-payment/blob/11.0/account_cash_invoice/wizard/cash_invoice_in.xml#L15, 
`domain="[('id', 'in', journal_ids[0][2])]"` should be replaced by `domain="[('id', 'in', journal_ids)]"`, and the same happens in
https://github.com/OCA/account-payment/blob/11.0/account_cash_invoice/wizard/cash_invoice_out.xml#L15

In v12 it's already fixed.
Will you create a PR in OCA/account-payment or should I do it?
