### ISSUE TITLE
8.0 Inherit of name_get of res.currency breaks pos_payment_terminal

### ISSUE THREAD

**Issue by alexis-via** [OCA/pos#36]
If you inherit the name_get of res.currency, it will break the module pos_payment_terminal (v8.0 branch), because in the JS code of the module, "self.pos.config.currency_id[1]" contains the result of the name_get() of res.currency.

Unfortunately, we don't have access to the "name" field of res.currency via self.pos.currency.name because "name" is not a pre-loaded field of res.currency in the POS ! I made a PR on odoo to fix this: https://github.com/odoo/odoo/pull/7367

When the PR on odoo will be accepted, we will be able to replace "self.pos.config.currency_id[1]" by "self.pos.currency.name" in pos_payment_terminal/static/src/js/pos_payment_terminal.js. I'll take care of that... but for the moment, we need to have the PR on odoo accepted.

**Comment by legalsylvain** [comment]
Fixed in #37.
