### ISSUE TITLE
[8.0][hw_telium_payment_terminal] status is not implemented

### ISSUE THREAD

**Issue by azmeuk** [OCA/pos#372]
[This line](https://github.com/OCA/pos/blob/8.0/hw_telium_payment_terminal/controllers/main.py#L272) shows that there is no way to know the status of the payment terminal.
For example, http://127.0.0.1:8069/hw_proxy/status always shows the terminal as "connecting", even when it is fully functional.

- A not-so-bad solution would be to display a message like "unknown status, your payment terminal might be OK" to not lead people to understand the the terminal is actually connecting.
- A good solution would be to really implement a way to check that the terminal is connected.

**Comment by fmdl** [comment]
can be close
