### ISSUE TITLE
[12] pos_order_management - black screen in the pos after installing

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/pos#379]
After installing the module it was impossible to see the pos screen. After loading products, the screen is black.

Ininstalling the module , the problem was solved.

**Comment by legalsylvain** [comment]
Hi. @fgarcia-humanoide. Are you talking about pos_order_mgmt module ? 
I just tested on runbot, with all pos modules installed, and all is OK.

Did you reproduced the bug on runbot ? could you provide the javascript log erors ? 

thanks a lot.

**Comment by rafaelbn** [comment]
Please @fgarcia-humanoide explain to steps to reproduce in **runbot**

I tested with no issue so I close, if you can reproduce in runbot the please ping me

![2019-07-24_21-38-10](https://user-images.githubusercontent.com/8736623/61823168-82ba1180-ae5b-11e9-9acf-645f790980b7.png)

Thanks
