### ISSUE TITLE
Prices are only updating after manual customer switch and only per item

### ISSUE THREAD

**Issue by deejayalbatros** [OCA/pos#382]
I have downloaded your module from the Odoo apps page: https://apps.odoo.com/apps/modules/10.0/pos_pricelist/
I am on CE 10 and followed all instructions to set up everything correctly.

Now if I make an order in the POS on the customer with the discount there is no direct visible price change in the order basket, only if I go back to customers menu, change to a non-discount customer and confirm, and then change again to the discount customer. Only then the prices are adjusted according to the price list. And that I have to do for every item...

I have no pos_cache plugin enabled or any other that might interfere.

[Here ](https://drive.google.com/open?id=1Bv4uWbzqrXOCnR2ti5ezQMoVFmtD6qq0)you will find a video of the issue where you can see the prices of the item changing after switching customers manually...

Thanks for your effort,
Janick

**Comment by legalsylvain** [comment]
Hi janick,

Tested on [OCA runbot](https://runbot.odoo-community.org/runbot/repo/github-com-oca-pos-184
). Seems bug confirmed.

regards.

Could you test the patch provided here : 
https://github.com/OCA/pos/pull/322
thanks.

CC : @Yajo, @chienandalu

**Comment by deejayalbatros** [comment]
replacing _options.product.price_ by _options.price_  works...
