### ISSUE TITLE
[11.0] pos_lot_selection generating wrong stock moves  and messing up inventory

### ISSUE THREAD

**Issue by hydrosIII** [OCA/pos#392]
I have wondered if to post this here as it is a suspicion. But I do not know where else to post it. So let me explain.

 I suspect that the module pos_lot_selection is generating wrong stock moves in odoo. So far I have detected in my system a great amount of errors in the inventory. I found this when comparing the tables in odoo 11 enterprise stock_move_line, where the actual moves of stock are recorded and the stock_quant table, the table that odoo uses to display the stock in the GUI. For this detection I have compared manually the tables stock_move_line where the actual stock move are recorded and stock_quant. 

I update the system every month with a new version of odoo. 

**The reason I suspect the module is somewhat responsible is because I am using odoo enterprise and this is the only non official  module I am using**

The error arises when I compare the sum of the stock of products recorded in each table. This sum should be equal, but it is not. I put here the sql script I have created to check this difference:

```
/*Gets the current entries in the location connected with pos*/
WITH incoming as (
SELECT product_id, Sum(qty_done)
FROM stock_move_line
WHERE location_dest_id=15
GROUP BY product_id
), outgoing AS
/* gets the current outgoing stock from one determined location*/
(SELECT product_id, Sum(qty_done)
FROM stock_move_line
WHERE location_id=15
GROUP BY product_id
/*puts the quantity of stock incoming aside from its outgoing quantity*/
), incomingvsoutgoing AS (
SELECT incoming.product_id AS id, incoming.sum AS incoming, outgoing.sum AS outgoing
FROM incoming
LEFT OUTER JOIN outgoing
ON incoming.product_id = outgoing.product_id 
/*Gets the difference of the incoming stock vs the outgoing stock to get the difference and supposed stock in that location*/
), comparison AS
(select id, Sum(incoming) AS quant_incoming, Sum(outgoing) AS quant_outgoing, Sum(incoming-outgoing) AS supposed_stock
from  incomingvsoutgoing
group by id
/*Get the quantity in that location from the stock_quant table, this table is used by odoo to display the current stock*/
), stock_qty AS 
( SELECT product_id, Sum(quantity) AS quant_stock_ontable
FROM stock_quant
WHERE location_id=15 
GROUP BY product_id
/*Gets side by side the calculated supposed quantity and the quantity from the stock_quant*/
), supposed_stock_vs_stock_on_table AS
(SELECT id,quant_incoming,quant_outgoing, supposed_stock, quant_stock_ontable
from comparison, stock_qty
WHERE comparison.id=stock_qty.product_id
/*substracts the difference of supposed stock - quant_stock_on_table to get the difference*/
), results AS 
(select supposed_stock_vs_stock_on_table.id, Sum(supposed_stock_vs_stock_on_table.quant_incoming) AS  quant_incoming, Sum(supposed_stock) AS supposed_stock, Sum(supposed_stock_vs_stock_on_table.quant_outgoing) AS quant_outgoing, Sum(supposed_stock_vs_stock_on_table.supposed_stock-supposed_stock_vs_stock_on_table.quant_stock_ontable) AS difference, Sum(quant_stock_ontable) AS quant_stock_ontable
from supposed_stock_vs_stock_on_table
group by id
/*adds the product barcode*/
), results_w_code AS (
select results.id, results.quant_incoming, results.quant_outgoing, results.difference, supposed_stock, default_code, product_tmpl_id,  quant_stock_ontable
from results, product_product
where results.id = product_product.id)
/*prints the results, adding the product name, and selecting just the products where the supposed stock is not equal to the stock in stock_quant table*/
SELECT results_w_code.id as product_database_id, results_w_code.quant_incoming, results_w_code.quant_outgoing, supposed_stock, results_w_code.quant_stock_ontable, difference, name as corrupted_product_name, product_template.default_code AS corrupted_product_code
from results_w_code, product_template
WHERE results_w_code.product_tmpl_id = product_template.id 
AND difference IS NOT NULL
AND difference <> 0
ORDER BY difference DESC;

```
.
Also I have noticed the following trends:

a) The error rate grows every month, adding new products and new errors every month.
b) These errors only occur in the location (15) that is my default location in my odoo config where the products are taken from to  sale them later in the point of sale. No other location is affected by inventory errors despite transactions.

So far I think there are three possibilities.
1) An error in the odoo core modules.
2) An error in this module.
3) I am missing something out.

**Comment by pedrobaeza** [comment]
Sorry, but unless you have an steps to reproduce a problem, suspicions don't serve for solving anything. Please use a demo instance and use it, comparing on each step, after getting the deviation.

**Comment by hydrosIII** [comment]
I am sorry Pedro Baeza, i have tried to exahustion to replicate the problem. I wlll try again I know is not enough. So I post it here. In a demo instance I cannot replicate the sales of a live instance. I suspect the problems arises only in some sales. So, it just appears with a lot of transactions. I suspect (again) This is the reason why I have not been able to replicate the problem Sorry. Feel free to close the issue, if you seem it is irrelevant.

**Comment by pedrobaeza** [comment]
Irrelevant is not the word, but useless as is it is. I hope the problem would be the module, easy to be solved, and not something deeper, but nothing can be investigated/solved without a way to reproduce the problem. Try to check complete Odoo logs for finding something that can lead you to a trace.

**Comment by hydrosIII** [comment]
Hello I have confirmed that it is not this module that is generating the error. The steṕs to replicate the error are just selling products. But it is not thos modules fault. You can close the ticket.

**Comment by hydrosIII** [comment]
The error is in the odoo official code, not this module.
