### ISSUE TITLE
[11.0] [pos_order_mgmt] Reprint ticket with archived products

### ISSUE THREAD

**Issue by Joaco1980** [OCA/pos#401]
When you try to reprint a ticket and one of the products has not been loaded into the POS because it has been archived or discontinued, an error pops up. I suppose it is to keep the function offline, but to find a ticket not loaded in the pos with the limit set if you have to be online.

I hope I have explained myself correctly, my English is not good at all ... ;-)

**Comment by pedrobaeza** [comment]
There's no easy solution to this, as this is out of control of the module itself. Unarchive that product, print, and archive it again.
