### ISSUE TITLE
POS margin 

### ISSUE THREAD

**Issue by ahmed22s885111qq** [OCA/pos#404]
HI
I USE ODOO 12 AND THERE IS A PROBLEM THAT THE MARGIN DOESNT EXIST IN POS ORDERS OR POS REPORTS .
HOW CAN I DO IT ?
PLEASE IF THERE IS A PICTURES OR A VIDEO TO SOLVE THIS PROBLEM IT WILL BE MUCH BETTER.
THANKS .

**Comment by legalsylvain** [comment]
Hi @ahmed22s885111qq. 

Welcome on github.
First, please don't use capital letter to make comments, as it's make the text less readable.

About your question, the module is available for the V12 serie here https://github.com/OCA/pos/tree/12.0/pos_margin

kind regards.

**Comment by ahmed22s885111qq** [comment]
Thanks.. but I don't understand the codes .is there video or pictures to
solve this?

في الخميس، ٢٤ أكتوبر، ٢٠١٩ ١٤:٢٤ Sylvain LE GAL <notifications@github.com>
كتب:

**Comment by legalsylvain** [comment]
hi @ahmed22s885111qq. sorry but this is not the right place to ask general question about how to install a module, or how to understand the code. 
Here, you can report problem, if you find some bug in OCA modules.

To understand the module, please refer to the documentation available on the odoo.com and odoo-community.org website.

**Comment by ahmed22s885111qq** [comment]
Ok thanks.

في الخميس، ٢٤ أكتوبر، ٢٠١٩ ١٤:٤٠ Sylvain LE GAL <notifications@github.com>
كتب:
