### ISSUE TITLE
POS Loyalty details on receipt

### ISSUE THREAD

**Issue by nabilelkadiri** [OCA/pos#408]
Hi,

I'm using the pos_loyalty module on Odoo v10 CE, everything is working fine but the lines that should be printed into the customer receipt.

Receipts are printed directly to the POS printer with no PosBox use.

I have a customized module altering the Receipt data to include a cash tax.

Would you please help?

Thank you

**Comment by chienandalu** [comment]
I'm not sure I understand your issue. Could you add further details of what's missing?

**Comment by Azlanburney** [comment]
Can you please tell that how can we add the points on receipt?

**Comment by chienandalu** [comment]
You should describe the issue with detailed steps to reproduce it in a standard instance (i.e.: runbot). Otherwise nobody is going to be able to help you.
