### ISSUE TITLE
POS combined products [13.0]

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/pos#426]
I am working on a new module for the odoo POS.
The module tries to solve the creation of combined beverages so common in our bars.
From the point of view of the products I have created a couple of modifications, the first is to create a second price, the price of the product when combined with another.

![image](https://user-images.githubusercontent.com/3088246/70735363-65a0b500-1d0e-11ea-993c-668af3e16390.png)

I have also created a relationship to indicate with which product families we can combine the drink.

![image](https://user-images.githubusercontent.com/3088246/70735560-c6c88880-1d0e-11ea-9eba-90a977b46c14.png)

We will have to indicate that the product is "combinable" so that when selected, we will see the products of the families with which we can combine our product.

![image](https://user-images.githubusercontent.com/3088246/70735819-422a3a00-1d0f-11ea-844f-d5f9a8e3652b.png)

Already from the side of the POS, when selecting a combinable product, a screen with the articles with which to make the combination is displayed.

![image](https://user-images.githubusercontent.com/3088246/70736200-178cb100-1d10-11ea-939f-d3f91480fbef.png)

The line item is generated without problems indicating which products have been combined and using as the sale price, the sum of the two products when combined.

![image](https://user-images.githubusercontent.com/3088246/70736416-8ec24500-1d10-11ea-98bc-be426aa49335.png)

So far, all good.

Now I would like to start the debate on several specific issues.

My intention was to create the sale of two different products "Gin Rives", in a line whose total is the sum of both products, and the "Coca-Cola" product that adds to the order lines but keep it hidden from the user, to do not confuse.

This idea poses a serious problem, if you decide to manually change the price of the product. Since the price of the combined I get it from the sum of the two products.

A solution would be not to include in the order the second product in this case the "Coca-Cola", but I don't like this idea because we would be falsifying reality and our statistics would not be reflecting the sale of a product, and it has really been used in the combination.

A possible solution, include the second product at zero price and keep it hidden from the user, and that the total amount of the product falls on the price of the first product or the "Gin Rives", but in the statistics the valuation of the second product would be unreal.

Another solution is to apply the manual change on the first product, and leave the second product intact at its original price, the latter is the one I like the most and I think it fits reality.

I want to open this debate to see what you think about this topic and study the possible solutions.

Thank you.

**Comment by legalsylvain** [comment]
Hi @manuelcalerosolis. Could you add the source code as a link ? 

thanks.

**Comment by manuelcalerosolis** [comment]
@legalsylvain I prepare the code and upload it, but now I would like to know what you think of the problem that I raise in the issue.

**Comment by legalsylvain** [comment]
Ok. Let me know when the code is available. It's easier for me to understand the design, seing the models and to test with the OCA runbot.
Feel free to make a WIP PR.
Kind regards.

**Comment by manuelcalerosolis** [comment]
Here is the code.

[https://github.com/manuelcalerosolis/pos_combinated_drinks](https://github.com/manuelcalerosolis/pos_combinated_drinks)

Regards.

**Comment by chienandalu** [comment]
Hi, Manuel.

One way to model this could be with variants, although if need to manage stock, it could be not enough. This is the product configurator for the POS: https://github.com/OCA/pos/pull/411

Another way, could be to base github.com/OCA/product-pack family in order to implement the backend logic on POS.

But if I understand fine, the point here is to have configurable kits of products. So I think your approach is missing some parts:

- To have, in one side, the combo product, which should be no stockable, with a proper flag on it.
- In the combo product you should be able to configure wich product categories and the max selectable quantity for each. So, for example: Alcoholic drinks: max 1, Fresh drinks: max 1
- In the combinable product side, a many2many to choose to wich combos can be applied
Then, when you sell in the POS you'd be doind a kind of soft Bill of Materials. Anyway, you should have the proper model and a link to the pos.order.line in order to discount it from the stock later.

Maybe a PR will help to debate on a more solid base :)

**Comment by manuelcalerosolis** [comment]
Hi, David.

Thanks for your time.

On the subject of product_pack, it is not useful, every time a drink is created, let's put a "new gin", it would have to make possible combinations with all the products, with which it can be combined, and vice versa, if it enters a new combinable drink update one by one, crazy.

That is why I believe in the relationship between the main product and a category, that is also solved very easily. Updates are automatic as long as the new product belongs to the category with which we establish the relationship.

I think our approach is different, I don't want to have to define combinations of products one by one, that would make it very heavy and complex.

My idea is that one product can be attached to another, with special prices if they are combined, or even allowed to be served without combining, at its usual price.

I do not understand the need to define the number of products that are combined, it would slow the selection of combinations, and time is money.

Regards.
