### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by edkroked** [OCA/pos#429]
I had installed version 12 on the QNAP on a fresh installation. I had install the package by normal way. But the screen stay black by opening the POS terminal. Can someone help me or tell me what is going wrong?

**Comment by legalsylvain** [comment]
Hi @edkroked. Seems you're not in the good place. if you have trouble with Odoo PoS module, please refer to the odoo repository. https://github.com/odoo/odoo or talk to your integrator.

you can also open the console log of your browser, to try to understand why it's not working.

kind regards.
