### ISSUE TITLE
[12.0] [pos_order_mgmt] erro

### ISSUE THREAD

**Issue by edkroked** [OCA/pos#431]
There is a style error in the POS when opening:
Style error
×
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /pos_order_mgmt/static/src/css/pos.css defined in bundle 'point_of_sale.assets'.

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot

**Comment by edkroked** [comment]
Which runbot you want; that I try?

**Comment by legalsylvain** [comment]
The runbot of the oca branch. You'll find the link here.

https://github.com/OCA/pos/blob/12.0/README.md

**Comment by edkroked** [comment]
Sorry that is only the readme file and there is nothing too run

**Comment by legalsylvain** [comment]
Guy, there is a link in the readme file. please click on it !

**Comment by edkroked** [comment]
After update the library it was fixed.
