### ISSUE TITLE
pos_remove_pos_category

### ISSUE THREAD

**Issue by jcarlosmontoya** [OCA/pos#46]
When installing this module, images of the product categories at the POS buttons are no longer displayed.
i'm going to add a PR.
Image:
![With image](https://cloud.githubusercontent.com/assets/7680456/9464264/e36635c2-4b22-11e5-9cdb-ac258af19112.PNG)

None:
![no image](https://cloud.githubusercontent.com/assets/7680456/9464265/e3873b1e-4b22-11e5-9347-f2b2f694232b.PNG)

Buttons:

![img3](https://cloud.githubusercontent.com/assets/7680456/9464335/5d9d6518-4b23-11e5-9546-d98ffe97ebdf.PNG)

![img4](https://cloud.githubusercontent.com/assets/7680456/9464342/6309305e-4b23-11e5-8300-ac1d4e598bef.PNG)

**Comment by legalsylvain** [comment]
WIP in #47

**Comment by legalsylvain** [comment]
#47 has been merged.
