### ISSUE TITLE
[12.0] [pos_order_mgmt] - Ticket date 

### ISSUE THREAD

**Issue by agavariat** [OCA/pos#469]
When I re-print the ticket it takes the actual date and not the date the ticket was printed.

I think that if I am re-print it shouldn't change any field. 

Regards!

![Captura de pantalla de 2020-03-14 10-18-31](https://user-images.githubusercontent.com/44479766/76684838-2fa8f080-65dd-11ea-9804-db09d6469d90.png)

**Comment by pedrobaeza** [comment]
What do you think, @chienandalu ? I'm not totally agree, as the ticket is new, but from an old order.

**Comment by legalsylvain** [comment]
I think user expect the same ticket.
The date should be the original one.

**Comment by chienandalu** [comment]
I think the same. Indeed in v11 it works like that. Your receipt screenshot doesn't look to me as the standard one. Did you modify the standard reports?

**Comment by RicardoNar** [comment]
> I think user expect the same ticket.
> The date should be the original one.

Yes I Agree, date should be the original. Its like reprinting an invoice. All data must be the same.

**Comment by kach200** [comment]
Hello, I also have this problem
If the client requests a reprint of a previous week, it must be the date the receipt was issued

**Comment by chienandalu** [comment]
> Hello, I also have this problem
> If the client requests a reprint of a previous week, it must be the date the receipt was issued

Can you reproduce it on an standard setup? (OCA Runbot)
