### ISSUE TITLE
Question reagrding flashing a new IOTBox

### ISSUE THREAD

**Issue by flotho** [OCA/pos#478]
Hi everyone,

I'm used to burn sd card thanks to the v8 branch of OCB. Yet on this v12 I can see that this repo is containing a hw_* module, 

Is there any recommendation, good way to proceed ? 
Does this folder https://github.com/OCA/OCB/tree/12.0/addons/point_of_sale/tools/posbox a good starting point for v12 ?

Any help would be appreciated 

Thanks

**Comment by chienandalu** [comment]
You can go with already built images by Odoo: https://nightly.odoo.com/master/posbox/iotbox/

**Comment by flotho** [comment]
Actually I want to add OCA modules like thelium, display etc...
So AFAIK, I need to run a specific script.

Am I wrong ?

**Comment by chienandalu** [comment]
Yes, if you want to have a pre-built image with them you have to build it.
Or you can tweak the IoTBox after it

**Comment by flotho** [comment]
isn't the Iotbox readonly ?

**Comment by chienandalu** [comment]
Here's a very good recipe to change edit the Iotbox config :) https://odoo-development.readthedocs.io/en/latest/admin/posbox/administrate-posbox.html#how-to-edit-config

**Comment by flotho** [comment]
@yelizariev produce always good resources.

Thanks, it will be easier

**Comment by flotho** [comment]
BTW, if anyone already solved this, from now I'm failing on this issue while building: 
```
'/home/florent/DEV/Odoo_Server_And_Libs/Servers_12/OCB/addons/point_of_sale/tools/posbox/overwrite_before_init/usr/bin/ngrok' -> '/home/florent/DEV/Odoo_Server_And_Libs/Servers_12/OCB/addons/point_of_sale/tools/posbox/root_mount/usr/bin/ngrok'
chroot: impossible d'exécuter la commande « /bin/bash »: Aucun fichier ou dossier de ce type

```
