### ISSUE TITLE
[hw]hw payment terminal :question regarindg the installation

### ISSUE THREAD

**Issue by flotho** [OCA/pos#483]
Hi @legalsylvain ,

great works for the hw module. I'm wondering if the installation process is complete : https://github.com/OCA/pos/tree/12.0/hw_telium_payment_terminal#id1
Isn't it necessary to add it in the load part ?
or maybe add server_wide_mod_le section in the conf file ?

Regards

**Comment by legalsylvain** [comment]
Hi @flotho. I will not be able to help you on that point. I use pywebdriver for the hardware part. 

maybe @alexis-via could help you ? 

kind regards.

**Comment by flotho** [comment]
Hi @legalsylvain ,

I succeeded in using this awesome module.
Thanks
