### ISSUE TITLE
Question regarding proper way to inherit hw driver module

### ISSUE THREAD

**Issue by flotho** [OCA/pos#494]
Hi,

I've succeed in making the IOT BOX displaying on the official raspberry pi display : https://www.kubii.fr/ecrans-afficheurs/1131-ecran-tactile-officiel-7-800x480-kubii-640522710829.html
For making it work I've been forced to change this method a bit https://github.com/OCA/OCB/blob/13.0/addons/hw_drivers/controllers/driver.py#L327

My totally newbie question here, is how to inherit this method properly as it is a thread because I would like to submit my work to the community.

Thanks

**Comment by legalsylvain** [comment]
Not so easy. You can do some monkey python patch but it's not very clean. Could you show the diff between your function and the original one ? 
thanks !

**Comment by flotho** [comment]
for sure, actually it's pretty simple (it only took to me 2 working days to conclude on this ;-) ):

This part has been added just before https://github.com/OCA/OCB/blob/13.0/addons/hw_drivers/controllers/driver.py#L346 

```
        if not len(display_devices):
            for match in finditer('Display Number (\d), type Main LCD', displays):
                  display_id = match.groups()
                  _logger.debug("Display id matched before subprocess %s" % display_id)
                  display_name = subprocess.check_output(['tvservice', '-nv', str(display_id)]).decode().rstrip().split('=')[1]
                  _logger.debug('========= After sub process %s' %  display_name)
                  display_identifier = sub('[^a-zA-Z0-9 ]+', '', display_name).replace(' ', '_') + "_" + str(x_screen)
                  
                  iot_device = IoTDevice({
                      'identifier': display_identifier,
                      'name': display_name,
                      'x_screen': str(x_screen),
                  }, 'display')
                  display_devices[display_identifier] = iot_device
            _logger.debug("======== Trying to %s" % display_devices)
```

And it worked like a charm.

**Comment by legalsylvain** [comment]
if you can not overload "normaly", you can monkey patch this way : (line 17 - 35)
https://github.com/OCA/reporting-engine/blob/12.0/bi_view_editor/models/models.py#L17

so call 
- call original function and get result
- apply your code. if found add your device. (and maybe remove the "fake" distant_display)
- return the updated result

can work... !
