### ISSUE TITLE
POS Frontend Orders reprint

### ISSUE THREAD

**Issue by kach200** [OCA/pos#502]
show all the orders of several sessions in the frontend
for version 12
print or return an order from another session
![all order](https://user-images.githubusercontent.com/56906165/84092897-f69ed300-a9b5-11ea-87d4-ff0931de88bd.png)

**Comment by chienandalu** [comment]
It would be a little bit absurd if could only return a sale to the same cashier you got it first, don't you think? :)

**Comment by kach200** [comment]
there are cases where only an administrator or supervisor user can reprint an order

Regards
