### ISSUE TITLE
missing "Send invoice by email" button

### ISSUE THREAD

**Issue by emavarela** [OCA/pos#506]
Hello community,

After installing the POS Invoice Send by Mail module I can't see the Send invoice by email button.
I have ticked the Send invoice by email option in the POS configuration, I have also deleted all history from the browser to avoid any cache issues but the button is still missing.

log files return no warning or error and F12 debug in chrome returns no warnings/errors

![config](https://user-images.githubusercontent.com/58047343/84554022-6251aa80-acec-11ea-9200-12c0648412cf.png)
![pos screen](https://user-images.githubusercontent.com/58047343/84554023-62ea4100-acec-11ea-87cc-5ae5496d17eb.png)

Thank you for your help.

**Comment by legalsylvain** [comment]
Hi. Couls you try to reproduce the bug on runbot ?

**Comment by emavarela** [comment]
Hi legalsylvain,

Thank you very much for your quick answer, I've performed a clean odoo12 installation and this time it worked flawlesly.
Thank you again.
Emanuel
