### ISSUE TITLE
cash in/out journal entry uses odoo server time and not user settings time

### ISSUE THREAD

**Issue by emavarela** [OCA/pos#507]
Hello community,

I was testing the pos_cash_move_reason module in odoo 12 and works fine for the exception that the movements created in the journals takes place using the odoo server time and not the user settings time.
This creates confusion with the end user and also leads to problems when creating reports because the point of sale closing balance and sales are all created using the user settings time.
This was tested in runbot (please see attached image). I set the timezome of the test user to Argentina (UTC-3) and the date the test took place is the 06-16-2020.
The sales are registered correctly in the date 06-16-2020 (which is correct by using the user timezone) but the cash-out movement was registered one day after because of the difference between server time and user time.
![pos_cash_move_reason wrong dateTime](https://user-images.githubusercontent.com/58047343/84843026-289adf80-b01d-11ea-9406-ec6fb6e35e0a.png)

Thank you!
Emanuel

**Comment by legalsylvain** [comment]
Hi @emavarela. I propose a patch. Could you test if all is ok, and approve the PR, if yes ? 

thanks !
