### ISSUE TITLE
[11.0] pos_order_mgmt -  taxes included or excluded in the price

### ISSUE THREAD

**Issue by Joaco1980** [OCA/pos#510]
The module reprints tickets well if taxes are included in the price. If you handle a tax without including it in the price, the reprint does not match the backend.

BACKEND:
<img width="948" alt="captura" src="https://user-images.githubusercontent.com/14363121/85599916-45529b00-b64d-11ea-8109-0407bcab87ae.png">

REPRINT:
![captura1](https://user-images.githubusercontent.com/14363121/85600249-92cf0800-b64d-11ea-8731-b383dbb0cb0f.jpg)

**Comment by chienandalu** [comment]
Does it happen when there's no discount?

**Comment by Joaco1980** [comment]
I think I know what happens, the unit price takes you from the product sheet? or the ticket?

We have two price fields in the product sheet:
list_price
professional_price
One is VAT included and the other VAT excluded

![captura](https://user-images.githubusercontent.com/14363121/85679891-1c242000-b6ca-11ea-85e5-de6beea9a178.jpg)
![captura2](https://user-images.githubusercontent.com/14363121/85679911-20e8d400-b6ca-11ea-9b25-8aa1aab8aff5.jpg)
![captura3](https://user-images.githubusercontent.com/14363121/85679937-26461e80-b6ca-11ea-8944-5dcdb3dc9a7b.jpg)

**Comment by chienandalu** [comment]
Ok. Try to reproduce it in a runbot. Otherwise, I'm afraid is a custom related issue and you'll have to adapt your code

**Comment by chienandalu** [comment]
Closing this issue. Feel free to reopen if you come up with reproduceable steps on runbot
