### ISSUE TITLE
Duplicate POS order

### ISSUE THREAD

**Issue by LcL54264** [OCA/pos#512]
Odoo version 12 - 
When I use POS to register, I will find that there are duplicate POS orders when I reconnect the network when I am disconnected.

![image](https://user-images.githubusercontent.com/62918960/86074166-f88d1b00-bab7-11ea-9dde-fb732f03c54d.png)

**Comment by chienandalu** [comment]
@LcL54264 is this an issue on some module of this repository?

**Comment by LcL54264** [comment]
> @ LcL54264在此存储库的某些模块上有问题吗？

Other modules are OK

**Comment by chienandalu** [comment]
Sorry. But to open your issue it must relate to a behavior induced by the modules contained in this repository.

**Comment by LcL54264** [comment]
> it must relate to a beha



> Sorry. But to open your issue it must relate to a behavior induced by the modules contained in this repository.



> 抱歉。但是要打开您的问题，它必须与此存储库中包含的模块引起的行为有关。

OK, thank you very much

**Comment by LcL54264** [comment]
> 抱歉。但是要打开您的问题，它必须与此存储库中包含的模块引起的行为有关。

OK, thank you very much
