### ISSUE TITLE
Product with leading zero EAN code read as double leading zero

### ISSUE THREAD

**Issue by fdedraco** [OCA/pos#53]
when I scan barcode of a product with leading zero in POS, POS read the input with double leading zero (unknown barcode).  it's not my scanner's fault i think (when i input the barcode on products it's valid). temp fix is adding zero on the barcode's field on product

**Comment by legalsylvain** [comment]
Hi, 
which OCA module are you using, that generate the problem ?

Thanks.

**Comment by fdedraco** [comment]
OCA? if you meant modules, i use all "default" modules bundled with odoo.

**Comment by legalsylvain** [comment]
I'm sorry, you're in an OCA repository :"Point Of Sale".
Bugs reported must be related to a module listed [here](https://github.com/OCA/pos).
If you have a bug with Odoo, You have to make a bug report on Odoo repository, [here](https://github.com/odoo/odoo/issues) (depending of the serie).

Kind regards.

**Comment by fdedraco** [comment]
i'm sure it's related with POS, since it only happen on POS web UI; if only i know how to generate log of it.

**Comment by legalsylvain** [comment]
Yes, but again, here it's just a repository of **extra** module for Point Of Sale. If you have a bug with the main module of PoS, please click on the link of my previous comment.
Your bug report is not in the good place.
kind regard.
