### ISSUE TITLE
[BUG] pos_order_return_traceability

### ISSUE THREAD

**Issue by yweng8111** [OCA/pos#587]
If I try to return a product, It doesn't take the tax from the origin pos line but from the actual tax-setting of this product.

e.g. usecase:
We used tax 16% in 2020 and the tax 19% in 2021 because of the policy.
I sold a product with tax 16% in last year. And the customer returns it in this year. The programme takes the 19% instead of 16% for this return order. Does somebody know how to fix this problem.

**Comment by legalsylvain** [comment]
Hi.
I think that maybe the bug depends of the countries. But indeed, in your country, and in france also, a refund should be done with the same VAT as the original sale.

Note : it's not a problem of ``pos_order_return_traceability`` but of ``pos_order_mgmt`` that you have also installed. (by dependency).

I don't know how to fix it. 
- did you tried to add vat information in the ``prepare`` function, here ? https://github.com/OCA/pos/blob/12.0/pos_order_mgmt/static/src/js/widgets.js#L331 
- Did you tried to make the refund in the back office ? 

kind regards.

CC : @chienandalu, @ivantodorovich

**Comment by chienandalu** [comment]
Mmm, I don't really know. As @legalsylvain pointed it might be correct depending on the legislation :confused:

**Comment by yweng8111** [comment]
Hi @legalsylvain,  You are right. I have noted the wrong module name. 
Actually I have already tried to extend the_prepare_orderlines_from_order_data for getting of the tax value from the old pos line. But the problem is that I can not use the tax in function [add_product](https://github.com/OCA/pos/blob/191c46c84ecb096a01b51daaab466875d7611c8e/pos_order_mgmt/static/src/js/widgets.js#L312)
I have also tried to extend the function add_product like this way. 
`var taxes_id = product.taxes_id;`
`product.taxes_id = line.taxes_id; <------ step 1 (set it with 16%)`
`add_product()....`
`product.taxes_id = taxes_id;       <------ step 2 (reset it with 19%)`
But it doesn't work.
if i just do step 1. it solves this problem. but the taxes_id of this product will still be 16%. If I continue selling this product, it always take the 16% for tax, until I reload the page. :(

**Comment by yweng8111** [comment]
I have already tried to make the refund in the back office. That works.

**Comment by legalsylvain** [comment]
Hi. @yweng8111. yes, it's a quite hard problem


In my mind : 
**solution A**

- add a field ``old_taxes`` on JS product model. you should overload also save to json and load to json function
- return this field in ``the_prepare_orderlines_from_order_data``
- overload ``add_product`` and changes taxes, if ``old_taxes`` is defined.

Not sure it woks... maybe you'll have trouble with fiscal position features...

**solution B**

When making a refund in the front office, check if the taxes are the same. If not raise a blocking error, and say to the user to make the refund in the backoffice.

kind regards.

**Comment by yweng8111** [comment]
Hi @legalsylvain,
I don't really understand your solution A. But I will try the solution B later. thanks

**Comment by kach200** [comment]
There is also a bug when a product change is made, it enters the product that is entering but does not generate the exit of the new product

**Comment by legalsylvain** [comment]
Hi could you open another issue, for the other bug, as it seems not related.
Thanks.
