### ISSUE TITLE
[v12] pos_order_to_sale_order pos not loading

### ISSUE THREAD

**Issue by JaimeEnriquezVivanco** [OCA/pos#588]
After I installing the addon and starting a new POS session nothing happens. The screen stays black after the POS session has loaded.

I have tried it in my computer (windows 10) and in a virtual machine (ubuntu)

I'm using Odoo 12.0-20201107 (Versión Community).

**Comment by legalsylvain** [comment]
Could you reproduce the problem on runbot ?

**Comment by legalsylvain** [comment]
closing because no response. Feel free to reopen if you can reproduce the bug on runbot.
kind regards.
