### ISSUE TITLE
when deleting an article from the POS, all article qty is reset to zero

### ISSUE THREAD

**Issue by woepwoep** [OCA/pos#59]
scenario:
entering the POS,
adding three articles A, B, and C
all with qty=1
then delete article C by pressing the DELETE key on the POSboard

results:
all articles A, B, and C have qty=0
and the cursor remains on article C

further tests:
press 12 (with the -default- QTY function still in place) will show all three articles A,B and C with a qty of 12, even though the cursor is only on article C.

after de-installing pos_pricelist and pressing F5 in the POS, 
everything works fine again.

**Comment by woepwoep** [comment]
Further testing reveals it is not a problem within pos_pricelist;
the problem only occurs in combination with a private module called pos_deposit.

So our first effort will be to track down the collision between those two modules;
if only pos_pricelist is installed and pos_deposit is not installed, all works fine.

Thx, Ron

**Comment by AdilHoumadi** [comment]
Check on your module if you have something which is related to the keyboard, a listener that catch event while keyin or keyup the numerical part of your keyboard.

**Comment by woepwoep** [comment]
could it be somewhere in this snippet?

file: static/src/js/pos.js
[...]

```
instance.point_of_sale.OrderWidget = instance.point_of_sale.OrderWidget.extend({
    set_value: function(val) {
        var order = this.pos.get('selectedOrder');
        currentOrderLines = order.get('orderLines');
        if (this.editable && order.getSelectedLine()) {
            var mode = this.numpad_state.get('mode');
            if( mode === 'quantity'){
                var uniqueid = order.getSelectedLine().get_line_uniqueId();
                order.getSelectedLine().set_quantity(val);

                (currentOrderLines).each(_.bind( function(item) {
                    dep_uniqueid = item.get_line_uniqueId();
                    if (dep_uniqueid == uniqueid) {
                        item.set_quantity(val)
                    }
                }, this));

            }else if( mode === 'discount'){
                order.getSelectedLine().set_discount(val);
            }else if( mode === 'price'){
                order.getSelectedLine().set_unit_price(val);
            }
        }
    },
});
```

**Comment by AdilHoumadi** [comment]
The two modules, override the same method set_value of OrderWidget.
You can improve your inheritance here by calling the super method.
You can check here : https://github.com/OCA/pos/blob/8.0/pos_pricelist/static/src/js/widgets.js#L22
I think your method clash with the other one.
Hope this help.

Thanks

**Comment by woepwoep** [comment]
excellent Adil,
i will forward this to our programmers.

thank you so much for your advice,
best regards, Ron

---

http://about.me/woepwoep

2015-10-14 15:44 GMT+02:00 Adil Houmadi notifications@github.com:

**Comment by AdilHoumadi** [comment]
@woepwoep, Any news about this issue ?

**Comment by woepwoep** [comment]
sorry, not yet.
there is some delay unfortunately.

i hope the delay will be over soon,
such that we receive an update of the module soon.

will let you know when we do.
thx, Ron

---

http://about.me/woepwoep

2015-10-28 18:57 GMT+01:00 Adil Houmadi notifications@github.com:

**Comment by woepwoep** [comment]
ok so the problem was indeed that there was no inheritance built into our private module pos_deposit.
i contacted another programmer to review the code and come up with a rewrite of pos_deposit.
testing today, will share the results when ready.

**Comment by woepwoep** [comment]
this module https://github.com/OCA/pos/pull/71 solves the issue.
thx @StefanRijnhart 
R

**Comment by StefanRijnhart** [comment]
This looks like a different issue, but not one that I have encountered

**Comment by woepwoep** [comment]
Stefan you are right, the issue was solved with the rewrite of our custom module "pos_deposit".
Thank you for the opportunity to clarify.
Best regards, Ron
