### ISSUE TITLE
Leave POS invoice unpaid

### ISSUE THREAD

**Issue by cscocca** [OCA/pos#590]
Hi, I need to leave invoice created from POS unpaid for certain allowed customer. Is it possible?

Thanks

**Comment by legalsylvain** [comment]
you can created confirmed sale orders via the point of sale with that module.
https://github.com/OCA/pos/tree/12.0/pos_order_to_sale_order

So, invoiced sale order can be opened, without payment.

**Comment by cscocca** [comment]
Ok It is useful... but it does not print the invoice in POS interface when created.

**Comment by legalsylvain** [comment]
> Ok It is useful... but it does not print the invoice in POS interface when created.

No but you can do it in the back office. (or send by email, depending on what the customer want).
