### ISSUE TITLE
12.0 > From pos_meal_voucher to generic voucher/check

### ISSUE THREAD

**Issue by gregory-moka** [OCA/pos#594]
Hello @legalsylvain :)

Happy to see you worked on this feature for the POS needs. I was working on a similar project for my needs, that could handle the "Holidays Check" (Chèque Vacances in french), and, as the process is really similar to the meal voucher, I was wondering if there were a way to refactor this addon to integrate the Holidays check.  

THe process is the same, a voucher with value, product that you can pay with, and barecode you can scan from POS. 
The only think that could be different, is when some shop allow to refund the difference, so, we need to handle with the cash journal.

![image](https://user-images.githubusercontent.com/45974412/106002711-bbbaee00-60b1-11eb-9775-88bdb36d9b1c.png)

So, what do you think about working on the generic implementation ?

Regards ;)

**Comment by legalsylvain** [comment]
Hi. Good question. I don't know exactly. 

Features are similar but lot of field should be duplicated. for exemple, ``meal_voucher_ok`` on ``product.template`` should be duplicated with ``holiday_voucher_ok``. the same for the product category. 
In fact, there is a lot of thing I don't know with check vacances. Is there a max amount by day, like for vouchers ?

Maybe we could envisage to have two modules in V12. ``pos_holiday_voucher`` and ``pos_meal_voucher``, and then, in a more recent version, make a third common module with common feature named ``pos_voucher_abstract`` and make two modules depends on this module.

regards.

**Comment by legalsylvain** [comment]
Hi @gregory-moka. Any update regarding my last comment ? 

kind regards.

**Comment by gregory-moka** [comment]
Hello @legalsylvain !
Sorry for my silent, I was really busy, and, I knew that you were too. I planed to work on it this year, but Holiday voucher are easier than meal voucher. It's only a way to pay, without amount limit.
My mistake is to think that we could make think generic, but, you're right, it could be a second addon specific for holiday voucher, and, we wont have to deal with specific behaviour needed by one or other payment method.

Do you need to work on this addon for you needs too ?

**Comment by legalsylvain** [comment]
Hi.

> Do you need to work on this addon for you needs too ?

For GRAP, no. It's a food cooperative, so Holiday voucher is not a valid payment method in our case. (Luckily because vouchers are generally a mess, in a logistic point of view, and in terms of cash flow !)

I can perform a service regarding that new feature if you want. contact me privately in that case. 

kind regards.

closing that issue, considering as answered.
