### ISSUE TITLE
Point Of Sale - Searchbox

### ISSUE THREAD

**Issue by pasgou** [OCA/pos#595]
The searchbox is activated when we click on a product or when we do select the searchbox.
Is there a way to make this functionality working differently ?
Indeed, on a tablet or phone without a keyboard, it's make no sense to display the virtual keyboard if the pos sale(wo)man click on products or scan a barecode. But this virtual keyboard is displayed when the searchbox is activated.

It could be interesting that click and barecode scanner don't activate this searchbox (or activate and deactivate it in the same millisecond if it's necessary).

**Comment by legalsylvain** [comment]
I think you should better open an issue against Odoo main repository, as your issue doesnt concern OCA module.
Don't you think ?

**Comment by pasgou** [comment]
It could be seen as an issue that concern Odoo, or it could be seen as an improvement to be done optionnaly in a new module that could change the behavior in the POS.

I don't know why but I think this problem has a bigger chance to be corrected in many versions if it is an OCA (or someone else) contribution .
