### ISSUE TITLE
[V12] stock interim & account receivable reconciliation not consistently reconciled? 

### ISSUE THREAD

**Issue by hitrosol** [OCA/pos#602]
I wonder to see the stock interim & account receivable journal items are not always reconciled in POS. 
Any clue to solve this using OCA's module ?

**Comment by legalsylvain** [comment]
Hi regarding @hitrosol. Regarding account reconciliation, I developed modules ``grap_pos_reconcile`` that reconciles PoS entries. 
the module is available here : https://github.com/grap/grap-odoo-custom-account/tree/12.0/grap_pos_reconcile
it depends on two other modules that generates less accounting moves. that is a quite custom implementation, but this come in the way of Odoo (in more recent version (13+), accounting moves are generated globally).

Feel free to test it.

kind regards.

I have no idea about stock interim. Could you explain more ? 

closing in the meantime. feel free to reopen.
