### ISSUE TITLE
pos_loyalty

### ISSUE THREAD

**Issue by yelizariev** [OCA/pos#61]
Can I create a PR to 9.0 branch with pos_loyalty module from saas-6 branch
https://github.com/odoo/odoo/tree/saas-6/addons/pos_loyalty
as it was moved to enterprise version
?

**Comment by pedrobaeza** [comment]
If there was a public version, you can start from it to create one module, while you keep the attribution.

**Comment by legalsylvain** [comment]
:+1: . You'll have to make this module OCA compliant. (pep8...) and let Author. But it's OK.
thanks !

**Comment by rafaelbn** [comment]
:+1:

**Comment by flotho** [comment]
+1

**Comment by yelizariev** [comment]
It seems like, someone took saas-6 version, prepared documentation and sale pos_loyalty module
https://www.odoo.com/apps/modules/8.0/pos_loyalty/

**Comment by legalsylvain** [comment]
I close this isssue, as it seems to be answered.

**Comment by yelizariev** [comment]
Let's consider this issue as a feature request. I suggest to reopen it and close only when some port the module. This issue contains a link to module to be ported. I think it's useful to keep it in opened issues.
