### ISSUE TITLE
v.12 pos journal img

### ISSUE THREAD

**Issue by Halsagabi** [OCA/pos#610]
Hello
Hope you're doing well
The images on pos cash/cards that i have uploaded don't appear only the basic main picture.. 
It appeared for couple of days which was weird but then it went back as it.
How could i fix it what do i have to make sure that is implemented?
thank you
Hanan

**Comment by chienandalu** [comment]
@Halsagabi what OCA module are you placing the issue for? What steps to reproduce the problem must be followed?

**Comment by legalsylvain** [comment]
Closing, as no answer.
