### ISSUE TITLE
Suggestion: pos_order_return 

### ISSUE THREAD

**Issue by emavarela** [OCA/pos#615]
Dear OCA community,

I've installed the module pos_order_mgmt and pos_order_return and they work great. Thank you for the hard work! 👍 

Just a suggestion to modify in /pos_order_return/models/pos_order.py :

'origin': self.returned_order_id.invoice_id.number,
'name': _(
'Return of %s' % self.returned_order_id.invoice_id.number),
'refund_invoice_id': self.returned_order_id.invoice_id.id,

Replace with:

'origin': **_self.returned_order_id.invoice_id.document_number_**,
'name': _(
'Return of %s' % **_self.returned_order_id.invoice_id.document_number_**),
'refund_invoice_id': self.returned_order_id.invoice_id.id,

With this small modification, the pos_order_return module will produce the same Document of Origin Value as if you were creating the credit note through the wizard in the frontend.

Again thank you very much for your hard work.
Regards,
Emanuel

**Comment by legalsylvain** [comment]
Hi @emavarela  thanks for your remarks. 
Could you make a Pull request ?
Thanks !

**Comment by emavarela** [comment]
Hi @legalsylvain  . Pull request created: #619 

Thank you!
Regards,
Emanuel

**Comment by emavarela** [comment]
Dear Community,

I've closed the pull request due to using another custom field, should have checked that before hand.

Cheers,
