### ISSUE TITLE
8.0 pos_pricelist incompatible with pos_customer_display

### ISSUE THREAD

**Issue by apik-hte** [OCA/pos#62]
When installing pos_pricelist & pos_customer_display, bug when launching web interface : 
![image](https://cloud.githubusercontent.com/assets/11721940/11065312/df8a224c-87c2-11e5-900e-28ded713090f.png)

**Comment by alexis-via** [comment]
@AdilHoumadi are you aware of this incompatibility ?

**Comment by AdilHoumadi** [comment]
I am not aware of this issue, we use this two modules in production and we don't have any problem.

**Comment by alexis-via** [comment]
I just made a test, and I didn't get this bug. So I close the bug.

@htetard If you have a precise scenario to reproduce the code with an up-to-date Odoo 8 and up-to-date OCA/pos, please post it here and we will re-open your bug report.
