### ISSUE TITLE
RFC: pos_order_return continuity

### ISSUE THREAD

**Issue by chienandalu** [OCA/pos#635]
With the current state of the art of `pos_order_mgmt`, which already supports returns and even uses the same field names for related refunded orders I'm not sure about the need of this module anymore.

What do you think? @dalonsod @legalsylvain @pedrobaeza @kirca @ivantodorovich 

TT27219

**Comment by ivantodorovich** [comment]
`pos_order_return` is focused on backend order refunds, and `pos_order_mgmt` is focused on refunds from pos ui.

I find `pos_order_return` is actually improving (one could even say fixing...) a core odoo feature. I wouldn't deprecate it for now (unless odoo improved it in core, I haven't checked)

**Comment by dalonsod** [comment]
I see `pos_order_return` useful, but incomplete. There's another addon (`pos_order_return_traceability`) that actually covers some return features for pos ui. As https://github.com/OCA/pos/tree/12.0/pos_order_return#known-issues-roadmap says, `pos_order_return` should be powered in v13 with these additional features. If achieved, `pos_order_mgmt` should be cover a basic return feature and `pos_order_return` (merged with `pos_order_return_traceability`) should provide a full backend & frontend return order support.

**Comment by chienandalu** [comment]
Ok, understood :+1: Thank to all!
