### ISSUE TITLE
[13] pos_default_partner not working

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/pos#636]
After configuring it, nothing happens

There  is no partner in the journal entrý

This is a big problem in spain because we need a VAT report that crashes if partner is not defined.

**Comment by fgarcia-humanoide** [comment]
I will try this modules

https://apps.odoo.com/apps/modules/13.0/pos_set_default_customer/

https://apps.odoo.com/apps/modules/13.0/mai_pos_default_customer/

https://apps.odoo.com/apps/modules/13.0/pw_pos_default_customer/

**Comment by chienandalu** [comment]
Please detail steps to reproduce in an OCA/pos runbot

**Comment by fgarcia-humanoide** [comment]
Instalation of odoo13 OCB with spanish localization 
Instalation of pos_default_partner
Creating a default customer with AEAT anonimous check
Seting this default customer in pos configuration
Make a sale on pos

Desired behaviour
In the journal the pos entry has a partner (default customer)

Real behaviour
In the journal the pos entry has no partner

**Comment by pedrobaeza** [comment]
That's not the goal of this module. The partner is on the pos.order.

**Comment by fgarcia-humanoide** [comment]
in v12 it works fine

look at "clients esporadics"


![Screenshot 2021-05-09 08 51 14](https://user-images.githubusercontent.com/7599709/117563241-c4559400-b0a4-11eb-81ce-c1a1ec4303d2.png)

**Comment by chienandalu** [comment]
But @fgarcia-humanoide you need to reproduce it in a community runbot of POS: https://runbot.odoo-community.org/runbot/repo/https-github-com-oca-pos-184

The questions to be answered:

- Do get the partner from the pos order in standard Odoo?. https://runbot.odoo.com
- If possitive, how is that different from what this module does?

**Comment by pedrobaeza** [comment]
As said, the module does what it does: put a default partner on the POS order. The transfer to the journal item was a "side effect" of how v12 does this process. Now in v13, Odoo groups the generated journal items, so no more that side effect.
