### ISSUE TITLE
Paging on product.product instead of product.template

### ISSUE THREAD

**Issue by ghost** [OCA/pos#64]
If a product has 100 variants it will be the only product on the page.  If 2 products add up to 100 variants they will be the only 2 on the page.  This wouldn't be that bad if you could get to the second page...but right now I have a category that has 10 products in it each with around 50 variants.  I only get to see 2 and cannot page to the rest.  So paging needs to also work off product.template in order for this module to be very useful.

**Comment by legalsylvain** [comment]
closed. duplicate : https://github.com/OCA/pos/issues/108
