### ISSUE TITLE
[V8] Pressing minus button increases POS order sequence

### ISSUE THREAD

**Issue by JGarcia-Panach** [OCA/pos#67]
I have tested in several instances of runbot.
- If the shopping cart is empty  and you press minus button, 
  ![antes del error](https://cloud.githubusercontent.com/assets/13234598/11498499/182163fa-9820-11e5-8c6b-0b2aae18fc77.JPG)
- Number of POS order sequence increases (each time you press)
  ![despues error](https://cloud.githubusercontent.com/assets/13234598/11498525/3d82a596-9820-11e5-931e-9ac2c331577a.JPG)
- Also, if you have selected some products and you press minus button, POS asks you about destroying current order.
  If you confirm, it also increases POS order sequence.

Thanks!

**Comment by pedrobaeza** [comment]
This is the standard behaviour, because you're removing the current POS order. As POS requires to have always on load order, it creates a new one each time.
