### ISSUE TITLE
OCA/PoS : Team member

### ISSUE THREAD

**Issue by legalsylvain** [OCA/pos#670]
Referring to : https://odoo-community.org/psc-teams/pos-59
The current responsible of the OCA/pos repository are : 

- Me, Sylvain Le Gal @legalsylvain 
- Pedro M Baeza @pedrobaeza 
- David Vidal @chienandalu 
- Rafael Blasco @rafaelbn 
- Alexis De Lattre @alexis-via 
- Markus Schneider @OSguard 

I think we could update this list a bit.

**Comment by legalsylvain** [comment]
- Do the people listed still want to be involved in the PoS project?
- would you see other regular contributors joining the group? I think for example of @ivantodorovich, @Fkawala, and @quentinDupont 

Ref, regarding recent contributions : https://github.com/OCA/pos/graphs/contributors?from=2019-01-01&to=2021-06-04&type=a

(don't know if there are statistics regarding reviews)

**Comment by chienandalu** [comment]
My particular vote y yes to both questions :slightly_smiling_face:

**Comment by pedrobaeza** [comment]
OK for me too to add that members.

**Comment by ivantodorovich** [comment]
Happy to join the team :)

**Comment by quentinDupont** [comment]
What an honour :blush:

**Comment by Fkawala** [comment]
That would be an honour for me as well! 😁

**Comment by legalsylvain** [comment]
Hi all,
I so asked to OCA support to : 
- add @quentinDupont, @ivantodorovich, @Fkawala to the team.
- remove @OSguard that is not active on odoo (and github more generally) since somes years.

It should active now.

For the newcomers please : 
- Please read the OCA convention, if not already done [here](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "[review](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review)" section.
- You have now merge right to all the branches. remember that usually, you _**never**_ have to click on "merge" button on github. Instead, use ``ocabot`` command. Take a look [here](https://github.com/OCA/oca-github-bot#commands) for how ocabot works.
- You can join the OCA forum, by clicking [here](https://matrix.to/#/+oca:matrix.org) and using Matrix (+Element). Alternatively, you can connect with discord if you prefer proprietary software. Once connected, you could join the OCA POS channel.

thanks !
