### ISSUE TITLE
How to edit the ticket for POS and for the POS box

### ISSUE THREAD

**Issue by flotho** [OCA/pos#68]
Hi everyone,

I was trying to change the POS ticket reciept. I fond the qweb views that were supposed to print the reciept but nothing seems to work.
Additionnaly, when a POSBOX is connected, where do I have to change the model? In the POSbox, in the Odoo Instance?
Any advice would be appreciated, regards

**Comment by alexis-via** [comment]
When you have a POSbox and a printer such as Epson TM-T20, you should change the ticket in the Odoo instance in odoo8/addons/point_of_sale/static/src/xml/pos.xml line 506

```
<t t-name="XmlReceipt">
```

**Comment by flotho** [comment]
Hi @alexis-via,
It's a great tip and I'm sure that @nono6677 will also be interested in this

**Comment by nono6677** [comment]
Yes, thank you guys

**Comment by Ark74** [comment]
@alexis-via Is it possible to a non posbox setup to use `<t t-name="XmlReceipt">` ?

It has many advantages on style.
