### ISSUE TITLE
pos_multiple_control, validate closing by managers group

### ISSUE THREAD

**Issue by GSLabIt** [OCA/pos#680]
@legalsylvain is there any chance to have specific group to validate cash control? 

I mean, cashier would never know the total transactions, otherwise they could keep money for themself if real closing balance is higher than theoretical.

So the idea is:

cashier enter ending balance and close session without validating closing.

cashier manager or sale manager will double check that: having all the money and electronic transaction from cashier and comparing with ending balance on session entered by cashier.

What u think?

**Comment by quentinDupont** [comment]
Hello @GSLabIt,

In our cooperative, we believe in transparency and trust in each other to improve workplace democracy and responsibility. We do not want to push to encourage capitalist patterns of mistrust but encourage in a direction of power sharing.

So for us, we have no interest in making this module more complex for these functionnalities.

That said, we understand that there are different interests and different situations of users of this module.

If this is important to you, we encourage you to develop the changes with the understanding that we are not inherently interested. Perhaps we can approve the changes if they are optional (but not the default) and do not add too much to the code that must be ported and maintained.

**Comment by GSLabIt** [comment]
> Hello @GSLabIt,
> 
> In our cooperative, we believe in transparency and trust in each other to improve workplace democracy and responsibility. We do not want to push to encourage capitalist patterns of mistrust but encourage in a direction of power sharing.
> 
> So for us, we have no interest in making this module more complex for these functionnalities.
> 
> That said, we understand that there are different interests and different situations of users of this module.
> 
> If this is important to you, we encourage you to develop the changes with the understanding that we are not inherently interested. Perhaps we can approve the changes if they are optional (but not the default) and do not add too much to the code that must be ported and maintained.
> 

Ok, for sure all will be optional. Maybe would be a new module depending on the existing one
