### ISSUE TITLE
[12.0] pos_user_restriction, issue when pos_restaurant is installed.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/pos#696]
Hi there,

when installing `pos_user_restriction` in combination with `pos_restaurant`, an error is raised: 

<img width="1209" alt="pos_rest" src="https://user-images.githubusercontent.com/11652845/128038736-8f80a0a2-69c0-44f0-891f-d4fc081fd565.png">

It seems like permission for `restaurant.floor` is needed.  

@eLBati @legalsylvain what you think about creating a new glue module `pos_restaurant_user_restriction` to add `restaurant.floor` permission?

Any other good ideas? 

Thx

**Comment by eLBati** [comment]
https://github.com/OCA/pos/pull/693 merged, can this be closed?

**Comment by chienandalu** [comment]
Thanks :)

**Comment by GSLabIt** [comment]
@eLBati well this is related to pos_restaurant, we should keep it open, imho
