### ISSUE TITLE
V13.0 V14.0 Generate Invoice unpaid from POS

### ISSUE THREAD

**Issue by ocandoe** [OCA/pos#698]
hello community, I'm looking for ways to generate invoices without payment from the point of sale in V13 but the same case happens in V14, I understand that odoo modified behavior that according to them "was wrong" on V12 but now those of us who came from V12  and used this functionality have a serious problem.

a issues is create en odoo https://github.com/odoo/odoo/issues/72752 but we don't know if one day they're going to include that functionality

is it why I come to you, is it possible to develop it?

**Comment by legalsylvain** [comment]
Hi @ocandoe. I answered in odoo/odoo#72752.

Feel free to reopen, if you want to add something.

regards.
