### ISSUE TITLE
[12.0] hw_telium_payment_terminal not working after inactivity

### ISSUE THREAD

**Issue by gregory-moka** [OCA/pos#701]
Hello,

**Configuration:**
I'm using `hw_telium_payment_terminal` to manage a DESK/5000 from POS (v12CE) thrue IOTBox (v18.12).

**Acutal behaviour:**
As I let my POS unused for a long time (1 night ~ 8hours), and as I want to open a new session, the POS is not able to send the amount on the payment terminal at all.
To correct this behaviour, I have to restart the IOTBox to be able to use it again.

**Solution ?**
I talk with my DESK/5000 supplier that told me that the POS has to frequently check if the terminal is here (initialisation ?) to prevent it to cut the USB connexion.

Is there a way to automate that connexion checking from IOTBox ?

@alexis-via @ivantodorovich

**Comment by gregory-moka** [comment]
@ivantodorovich Is it possible to have a look at this please ?

**Comment by eguane** [comment]
Hi you can maybe help me about how you configure i ? I try several option with desk/5000 but can't find the goood one. 
USB mode activated, Baud 9600, data bits 7, parity even, stop bits 1, flow control rts. Odoo 14CE, iot version 21.04. 

![image](https://user-images.githubusercontent.com/35990301/139101867-2c62b4ef-357e-49c2-88c4-f65f8ea5e9bc.png)

Rgds
