### ISSUE TITLE
[12.0] pos_margin doesn't handle inclued/excluded taxes

### ISSUE THREAD

**Issue by gregory-moka** [OCA/pos#707]
Hello,
I've got a strange behaviour on `pos_margin` addon.

**The case :**
I have a product that 

- I buy 28,8€ tax included, 
- I sell it 32€ tax included
- The margin rate is 10%
- The margin is 3,2€

When I set the product with all excluded taxes, all seems ok : 

**General informations :** 

![image](https://user-images.githubusercontent.com/45974412/133090028-e46df496-05ac-40aa-a55d-11629b5e17cc.png)

**Purchase tab :**

![image](https://user-images.githubusercontent.com/45974412/133090161-248da80d-212d-4a1e-85cb-0ef49b75d8ef.png)

But, as soon as set the prices with included taxes, all is going weird : 

**General informations :** 

![image](https://user-images.githubusercontent.com/45974412/133090340-d0d86587-0e77-46fa-8033-c7930825e04a.png)

**Purchase tab :**

![image](https://user-images.githubusercontent.com/45974412/133090404-37357360-57b0-4f78-bc5f-b3199f8447b1.png)

Is their something that I don't catch on the addon settings, or the addon is mainly done for exluded taxe sales ?
Thank you for help 😄

**Comment by gregory-moka** [comment]
And, to go further, on variant products, the issue seems to be different as the variant doesn't manage taxe on ``product.product``. We have weird presentation : 
![image](https://user-images.githubusercontent.com/45974412/133096190-74efe198-f827-45b8-a3c5-c9929eb6a5fc.png)

**Comment by legalsylvain** [comment]
Hi. I guess you don't point the good module (and repo). AFAIK, the theoritical margin is introduced in this module.
https://github.com/OCA/margin-analysis/tree/12.0/product_standard_margin

could you create an issue in the according repo ? could also make a test on the OCA runbot and send the link ? I use to use this module for both configuration (vat excl / vat incl), and didn't face any trouble. (V12 Community).

kind regards.
