### ISSUE TITLE
[14.0] Receipt print with QZ Tray

### ISSUE THREAD

**Issue by angelmoya** [OCA/pos#710]
Hi, I'm testing alternatives to print receipt without posbox (iotbox) or direct print.

[https://qz.io/](https://qz.io/)

I tested QZ tray, that has two components.
1. Java app that you need to install on POS (Linux, Windows or Mac OS)
2. Javascript library that must be integrated on Odoo POS

I was testing receipt printing on POS, but I noticed that is printing receipt as image instead of raw ESCPOS printing.

This work is in progress but if someone want to check or have better solution we can talk about

**Comment by legalsylvain** [comment]
Hi @angelmoya. 

I don't know qz. It seems interesting ! 

At GRAP, we are using "pseudo OCA" library, named pywebdriver. it is hosted by akretion, used by some OCA companies, like Acsone.

here you can find the lib https://github.com/akretion/pywebdriver/

The point 2 is not required in pywebdriver. (the objective is to emulate a pos/awesome/iot/box but in a keep it simple logic.

feel free to contribute, if you are interested.

**Comment by angelmoya** [comment]
Thanks for the info @legalsylvain , did you do raw EXCPOS ticket printing?

**Comment by legalsylvain** [comment]
> Thanks for the info @legalsylvain , did you do raw EXCPOS ticket printing?

I think @PierrickBrun is the right person to answer you.

**Comment by PierrickBrun** [comment]
Hi @angelmoya .
In pywebdriver Raw Esc/Pos works but Odoo  POS only sends images starting from v13.0.

b64 images embedded in escpos works well tbh. But you could also generate esc/pos xml and send it if you really needed to (like in v12.0)
