### ISSUE TITLE
Pos_margin the value of margin the best be negative or positive

### ISSUE THREAD

**Issue by MaroufAlkathire** [OCA/pos#715]
when i was read the source code of module Pos_margin and want to change calculate the margin from cost price to sale price so i note all my numbers of margin be negative so my question the value of margin the best be negative or positive ? 

if purchase_price = 100 and line.qty = 1 and price_subtotal  = 86.96 

note price_subtotal i guess always be less then the purchase_price .

in source code calculate margin = line.price_subtotal - (purchase_price * line.qty)

the result of margin will be = 86.96 - 100 = -13.04 

i don't know this equation is correct or not

**Comment by chienandalu** [comment]
Well, if you sell at a lower price that your cost, you're losing money, so it's correct indeed. At the end, when you aggregate all your sale margins, you should see a positive value. For instance, if you offer a 100% discount you'll have a negative margin for the whole subtotal, but it should be compensated with other items you sell or you'll run out of bussiness very soon :sweat_smile: Anyway, it's just bussiness logic outside of Odoo.
