### ISSUE TITLE
this.compute_all is not a function

### ISSUE THREAD

**Issue by chuckyroy** [OCA/pos#72]
it just freeze My POS, I will have to drop the DB to start a new one
![image](https://cloud.githubusercontent.com/assets/10263326/12010400/546a02ba-ac73-11e5-8d38-abd7b7d9663b.png)

**Comment by legalsylvain** [comment]
Please provide extra information like version of your Odoo instance, modules installed, etc.
Regards.

**Comment by chuckyroy** [comment]
Nothing really, it is a test oddo v.8, so pretty much the basics, here is all installed apps

![image](https://cloud.githubusercontent.com/assets/10263326/12010685/05695bfa-ac7f-11e5-88c5-8c06c6364cbc.png)

**Comment by chuckyroy** [comment]
Note that I uninstalled the POS_pricelist so you don't see it in the printscreen

**Comment by legalsylvain** [comment]
thanks.
Well, did you full-refreshed the cache of your browser after have uninstalled pos_pricelist ?
If no OCA module are installed, I don't see the reason to report a bug here. Could you be more precise ? thanks.

**Comment by chuckyroy** [comment]
Hi, I installed it twice on two different DBs and got the same error message.

**Comment by chuckyroy** [comment]
Hi I just reinstalled the app, restarted the PostgreSQL and refreshed the cashe. got the same error message.

**Comment by alexis-via** [comment]
@chuckyroy could you list all the modules you have installed, not just the apps ? Because we don't see the OCA POS modules you have installed...

**Comment by chuckyroy** [comment]
Here is the complete list. Please confirm you received is order.

CRM

OpenERP SA

8.0.1.0

Installed

Social Network

OpenERP SA

8.0.1.0

Installed

Online Billing

OpenERP SA

8.0.1.0

Installed

Hardware Proxy

OpenERP SA

8.0.1.0

Installed

Barcode Scanner Hardware Driver

OpenERP SA

8.0.1.0

Installed

Point of Sale

OpenERP SA

8.0.1.0.1

Installed

Point of Sale Discounts

OpenERP SA

8.0.1.0

Installed

Accounting and Finance

OpenERP SA

8.0.1.1

Installed

Sales Management

OpenERP SA

8.0.1.0

Installed

Warehouse Management

OpenERP SA

8.0.1.1

Installed

WMS Accounting

OpenERP SA

8.0.1.1

Installed

Instant Messaging

OpenERP SA

8.0.1.0

Installed

Purchase Management

OpenERP SA

8.0.1.1

Installed

Employee Directory

OpenERP SA

8.0.1.1

Installed

Time Tracking

OpenERP SA

8.0.1.0

Installed

Timesheets

OpenERP SA

8.0.1.0

Installed

eInvoicing

OpenERP SA

8.0.1.1

Installed

Anglo-Saxon Accounting

OpenERP SA, Veritos

8.0.1.2

Installed

Template of Charts of Accounts

OpenERP SA

8.0.1.1

Installed

Financial Reports - Webkit

Camptocamp

8.0.1.1.0

Installed

Analytic Accounting

OpenERP SA

8.0.1.1

Installed

Password Encryption

['OpenERP SA', 'FS3']

8.0.2.0

Installed

Signup

OpenERP SA

8.0.1.0

Installed

Base

OpenERP SA

8.0.1.3

Installed

Automated Action Rules

OpenERP SA

8.0.1.0

Installed

IBAN Bank Accounts

OpenERP SA

8.0.1.0

Installed

Base import

OpenERP SA

8.0.1.0

Installed

Initial Setup Tools

OpenERP SA

8.0.1.0

Installed

VAT Number Validation

OpenERP SA

8.0.1.0

Installed

Dashboards

OpenERP SA

8.0.1.0

Installed

IM Bus

OpenERP SA

8.0.1.0

Installed

Calendar

OpenERP SA

8.0.1.0

Installed

Claim on Deliveries

OpenERP SA

8.0.1.0

Installed

Claims Management

OpenERP SA

8.0.1.0

Installed

Currency Rate Update

Camptocamp

8.0.0.7

Installed

Decimal Precision Configuration

OpenERP SA

8.0.0.1

Installed

Delivery Costs

OpenERP SA

8.0.1.0

Installed

Electronic Data Interchange (EDI)

OpenERP SA

8.0.1.0

Installed

Email Templates

OpenERP SA

8.0.1.1

Installed

Email Gateway

OpenERP SA

8.0.1.0

Installed

Attendances

OpenERP SA

8.0.1.1

Installed

Invoice on Timesheets

OpenERP SA

8.0.1.0

Installed

Odoo Live Support

OpenERP SA

8.0.1.0

Installed

Canada - Accounting

Savoir-faire Linux

8.0.1.2

Installed

Payment Acquirer

OpenERP SA

8.0.1.0

Installed

Transfer Payment Acquirer

OpenERP SA

8.0.1.0

Installed

Portal

OpenERP SA

8.0.1.0

Installed

Portal Claim

OpenERP SA

8.0.0.1

Installed

Portal Sale

OpenERP SA

8.0.0.1

Installed

Portal Stock

OpenERP SA

8.0.0.1

Installed

Procurements

OpenERP SA

8.0.1.0

Installed

Just In Time Scheduling

OpenERP SA

8.0.1.0

Installed

Products & Pricelists

OpenERP SA

8.0.1.1

Installed

Report

OpenERP SA

8.0.1.0

Installed

Webkit Report Engine

Camptocamp

8.0.0.9

Installed

Resource

OpenERP SA

8.0.1.1

Installed

Opportunity to Quotation

OpenERP SA

8.0.1.0

Installed

Sales and Warehouse Management

OpenERP SA

8.0.1.0

Installed

Sales Teams

OpenERP SA

8.0.1.0

Installed

Share any Document

OpenERP SA

8.0.2.0

Installed

Invoice Picking Directly

OpenERP SA

8.0.1.0

Installed

Warehouse Management: Waves

OpenERP SA

8.0.1.0

Installed

Web

```
8.0.1.0
```

Installed

Web Calendar

OpenERP SA, Valentino Lab (Kalysto)

8.0.2.0

Installed

OpenERP Web Diagram

```
8.0.2.0
```

Installed

Web Gantt

```
8.0.2.0
```

Installed

Graph Views

```
8.0.3.0
```

Installed

Base Kanban

```
8.0.2.0
```

Installed

Gauge Widget for Kanban

```
8.0.1.0
```

Installed

Sparkline Widget for Kanban

```
8.0.1.0
```

Installed

Tests

```
8.0.2.0
```

Installed

View Editor

```
8.0.2.0
```

Installed

**Comment by legalsylvain** [comment]
Hi @chuckyroy, 
Could you improve your last comment, reducing the size of your comment. (currently unreadable) and set setting technical name of each module.

regards.

**Comment by aitorbouzas** [comment]
Same error here. I'm using an Odoo 8 preinstalled into a bitnami VM. Maybe it's some old code or an maybe an addon needs to be updated.

**Comment by aitorbouzas** [comment]
Also, before this error I had one about permissions with the "account.fiscal.position" object. Even though the user running the pos had all permissions, the POS could not be opened due to this error. I just deactivated the rule to be able to test this module.

**Comment by osadmn** [comment]
Hi, same issue here (Version 8.0-a2115ef) ...

TypeError: this.compute_all is not a function
    at module.Orderline.module.Orderline.extend.get_all_prices (http://localhost:8069/web/js/web.assets_backend/71ff1a8:4533:420)
    at module.PosDB.module.PosDB.extend.add_products (http://localhost:8069/web/js/web.assets_backend/71ff1a8:4521:345)
    at prototype.(anonymous function) [as add_products](http://localhost:8069/web/js/web.assets_common/ca89443:1088:595)
    at Object.module.PosModel.Backbone.Model.extend.models.loaded (http://localhost:8069/web/js/web.assets_backend/71ff1a8:4291:3554)
    at Object.<anonymous> (http://localhost:8069/web/js/web.assets_backend/71ff1a8:4296:48)
    at Object.<anonymous> (http://localhost:8069/web/js/web.assets_common/ca89443:249:688)
    at fire (http://localhost:8069/web/js/web.assets_common/ca89443:243:299)
    at Object.self.fireWith [as resolveWith](http://localhost:8069/web/js/web.assets_common/ca89443:248:198)
    at Object.<anonymous> (http://localhost:8069/web/js/web.assets_common/ca89443:249:879)
    at fire (http://localhost:8069/web/js/web.assets_common/ca89443:243:299)

List of currently installed modules attached (csv)
[ir.module.module.txt](https://github.com/OCA/pos/files/284583/ir.module.module.txt)
.

**Comment by legalsylvain** [comment]
Closing issue due to no response from my last comment : https://github.com/OCA/pos/issues/72#issuecomment-177217367

@Softdil about that point, see https://github.com/OCA/pos/issues/112

regards.
