### ISSUE TITLE
[14.0] pos_payment_change > User & Admin can't change payment

### ISSUE THREAD

**Issue by gregory-moka** [OCA/pos#724]
Once the **POS User** or **POS Admin** want to change the payment, on the validation screen, the following error is showing : 

> not able to access to records 'action window' (ir.actions.act_window)

Those roles are missing on POS user group : 
`ir_actions_act_window_system`
`ir_actions_act_window_close_group_system`
`ir_actions_act_window_view_group_system`

**Comment by legalsylvain** [comment]
Just tested on runboat without error. are you sure it is related to ``pos_payment_change`` ? 

regards.
