### ISSUE TITLE
[13.0] pos_session_pay_invoice: wrong behavior when matching pos payments 

### ISSUE THREAD

**Issue by dortunbo** [OCA/pos#729]
#674 @etobella @dsolanki-initos @fshah-initos @ivantodorovich Here I show a wrong behavior I've found while checking the payments of invoices paid at POS. Some of them have more than one payment, and one of them has the same amount as others invoices paid in the same session. It happens the same with bills. I hope you can find the cause oh this behavior.

Thanks,

https://user-images.githubusercontent.com/68110924/142725578-ef3d2783-201f-4103-800e-834a442c91d1.mp4

**Comment by ivantodorovich** [comment]
Indeed, sorry I missed it

@olgamarcocb could you have a look?
