### ISSUE TITLE
pos_product_template DOM error

### ISSUE THREAD

**Issue by shawnvarghese** [OCA/pos#73]
The following message appears when loading POS.
"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('http://127.0.0.1:8069')"

Possibly due to DOM manipulation as mentioned in the source code (for click_set_attribute_handler() and click_reset_attribute_handler() functions)

POS crashes after sometime due to this bug.

**Comment by legalsylvain** [comment]
Could you mention wich version of Odoo you are using. (odoo / OCA). revision... thanks.

**Comment by shawnvarghese** [comment]
Yes, sorry... Build Odoo 8.0-20151016 . I'm using the OCA pos_product_template module .

![image](https://cloud.githubusercontent.com/assets/10218181/12089219/ff284b06-b2fb-11e5-9dd2-cc8be9439098.png)

**Comment by shawnvarghese** [comment]
Could someone please help rectify this issue. The whole session crashes and the user has to log back into Odoo because of the bug.

**Comment by shawnvarghese** [comment]
Please let me know if there are any details I need to provide for this bug. Would be very grateful to anyone who can help fix it, as the code is in our production server and is causing serious problems.

**Comment by shawnvarghese** [comment]
I think the issue arises due to some part in the following code snippet. But I am not sure what it does or how it should be rectified. Any help would be highly apprecitated! 

```

`init: function(parent, options) {
            var self = this;
            this.attribute_list = [];
            this.product_template = null;
            this.click_set_attribute_handler = function(event){
                /*TODO: Refactor this function with elegant DOM manipulation */
                // remove selected item
                parent = this.parentElement.parentElement.parentElement;
                parent.children[0].classList.remove('selected');
                for (var i = 0 ; i < parent.children[1].children[0].children.length; i ++){
                    elem = parent.children[1].children[0].children[i];
                    elem.children[0].classList.remove('selected');
                }
                // add selected item
                this.children[0].classList.add('selected');
                self.__parentedParent.variant_list_widget.set_filter(this.dataset['attributeId'], this.dataset['attributeValueId']);
            };
            this.click_reset_attribute_handler = function(event){
                /*TODO: Refactor this function with elegant DOM manipulation */
                // remove selected item
                parent = this.parentElement;
                parent.children[0].classList.remove('selected');
                for (var i = 0 ; i < parent.children[1].children[0].children.length; i ++){
                    elem = parent.children[1].children[0].children[i];
                    elem.children[0].classList.remove('selected');
                }
                // add selected item
                this.classList.add('selected');
                self.__parentedParent.variant_list_widget.reset_filter(this.dataset['attributeId']);
            };
            this._super(parent, options);
        },`
```

**Comment by shawnvarghese** [comment]
Could anyone please help fix this? The POS keeps crashing because of this.

**Comment by legalsylvain** [comment]
Hi @shawnvarghese. Sorry I can't help you. I'm not expert in DOM manipulation. Maybe @hparfr will have good proposal to do.

regards.

**Comment by hparfr** [comment]
Is this issue still occurring ?
