### ISSUE TITLE
price are not show with taxes on POS

### ISSUE THREAD

**Issue by tboulogne** [OCA/pos#75]
module: pos_pricelist
version: 8.0

**Steps to reproduce**
-  no particular step.

**Current behavior**
prices shown without taxes on POS. Sales taxe are setup on products
No error dialog or line in logging files

**Expected behavior**
price including tax on POS

Do you have any tips to debug and solve this please ?

**Comment by JGarcia-Panach** [comment]
Have you tried "Price With Taxes" in Point of Sale configuration?

If you have, close session and start a new one.

If closing session does not help, you may not have taxes configuration in your product.

**Comment by tboulogne** [comment]
Thanks for your answer.

Price with Taxes checked.
http://prntscr.com/9swuzy

taxes setup on products
http://prntscr.com/9swuqb

But price show exclusive taxes even after cleaning and refresh session...
http://prntscr.com/9swui8
http://prntscr.com/9swu63

Do you have any over tips i could try to debug ?

Thanks for help.

regards

---

_From:_ Javier García-Panach
_Sent:_ Thursday, Jan 21, 2016 1:07:24 PM CET
_To:_ OCA/pos
_Cc:_ Thierry BOULOGNE
_Subject:_ [pos] price are not show with taxes on POS (#75)

**Comment by JGarcia-Panach** [comment]
Hi Thierry, 
I have installed pos_pricelist in a clean instance of odoo (just pos_pricelist, with custom accounting package) to try this. I post here the results:

**Create a product:**
![1 1](https://cloud.githubusercontent.com/assets/13234598/12480536/5bc4e5be-c043-11e5-8bb9-4c3e71da0386.JPG)

**Start a session in POS**
We have now the product without taxes.
![3](https://cloud.githubusercontent.com/assets/13234598/12480569/9bf4d91e-c043-11e5-94c0-7f8409a5143b.JPG)

**Close session**
![1](https://cloud.githubusercontent.com/assets/13234598/12480579/ab659d20-c043-11e5-9630-d4d359957414.JPG)

![2](https://cloud.githubusercontent.com/assets/13234598/12480582/aeddf8b2-c043-11e5-953f-5f8e6e288663.JPG)

**Check "Price With Taxes" in configuration**, and open a new session.
![6](https://cloud.githubusercontent.com/assets/13234598/12480612/e4039ed4-c043-11e5-93e0-cafb569db9d9.JPG)

**Now, price with taxes is shown**
![4](https://cloud.githubusercontent.com/assets/13234598/12480637/fb17bde4-c043-11e5-99e0-e907da2f9aa1.JPG)

As you see, it works for me.

Regards

**Comment by tboulogne** [comment]
thanks.

Not working for me on the production side.
I will git it another try

---

_From:_ Javier García-Panach
_Sent:_ Thursday, Jan 21, 2016 1:37:11 PM CET
_To:_ OCA/pos
_Cc:_ Thierry BOULOGNE
_Subject:_ [pos] price are not show with taxes on POS (#75)

**Comment by JGarcia-Panach** [comment]
You can try these two PRs from Antiun,  maybe one of them could suit you.
https://github.com/OCA/pos/pull/33
https://github.com/OCA/pos/pull/38

But, as they say here, https://github.com/OCA/pos/pull/39#issuecomment-126008362
those PRs are included in pos_pricelist and with a better implementation

**Comment by JGarcia-Panach** [comment]
Hey @tboulogne, try checking "Taxes included in price" inside every tax, in:
Invoicing/Configuration/Taxes.

It seems that if you have this check selected, the one included in the point of sale does not matter.
Please, correct me if I'm wrong.

Regards.

**Comment by legalsylvain** [comment]
in fact, check taxes included on each taxes should fix your problem.

kind regards.

**Comment by qupro** [comment]
Same @tboulogne  problem and same @JGarcia-Panach solution,  but checking "Taxes Included in price" in tax affects more functionalities like Invoicing. 

IMHO this results quite confusing , specially in invoices, since people is use to see price + tax = amount and not price - tax = amount. An example of last case:
![test](https://cloud.githubusercontent.com/assets/5942916/20578849/a8e921c0-b1c9-11e6-8f16-d8a0069b405e.png)
In another hand , price included in POS is good choice because final costumers and cashiers talk about final prices.

@legalsylvain I think that what happens here is that check "Taxes Included in price" in taxes works as defined, but "Price with taxes" in POS is not working.

edit: Sorry , I have just realized that you are using v8 and me v9, not sure any diferences regarding this
