### ISSUE TITLE
[Framework] PoS refactor for V16

### ISSUE THREAD

**Issue by legalsylvain** [OCA/pos#753]
Hi all PoS developpers and @OCA/pos-maintainers 

For your information, a pending PR is done against Odoo/master (future V16). The refactor is quite huge. (166 files changed) 
![image](https://user-images.githubusercontent.com/3407482/151134027-3349f23a-8557-4fad-a9e5-26df763c7375.png)

Feel free to review it, comment, etc..
https://github.com/odoo/odoo/pull/82461

kind regards.

**Comment by ivantodorovich** [comment]
Thanks for the news!
This is great, backbone was so outdated

**Comment by chienandalu** [comment]
Really big changes there :upside_down_face:

**Comment by legalsylvain** [comment]
Yes... porting modules to V16 will require works !
Hope pos framework will be stable in the futur.
