### ISSUE TITLE
Cash control dissapeared in Odoo 9 

### ISSUE THREAD

**Issue by mamolas** [OCA/pos#76]
Odoo 9 has Documentation showing cash control option in point of sale settings. But I can not find cash control option for point of sale settings. I have tried different configurations but no gain so far. I am looking for that Red Rectangle option :(
![image](https://cloud.githubusercontent.com/assets/4855042/12555227/2164654e-c34e-11e5-9d5d-fe8d1760981c.png)
Anybody know how to enable the cash control option for point of sale. Or anybody can confirm if this option is available only for Enterprise version. I am using community version.

http://stackoverflow.com/questions/34719493/how-to-enable-cash-control-option-in-odoo-9

**Comment by legalsylvain** [comment]
Hi @damodaranudas,

You should ask your question on Odoo github here https://github.com/odoo/odoo.git

Here is a repo for extra modules around Odoo PoS. If you want to develop a feature that manage cash control, please feel free to propose a PR here. 

Kind regards.
