### ISSUE TITLE
pos_payment_terminal working with wireless telium

### ISSUE THREAD

**Issue by cvinh** [OCA/pos#781]
Dear @OCA/pos-maintainers 
Sorry if it's not the right place to ask that question
Has anybody already tried to setup pos_payment_terminal with Ingenico wireless terminal ?
Thank you in advance

**Comment by legalsylvain** [comment]
hi @cvinh. 

It's not about the ``pos_payment_terminal`` but about the ``hw_telium_payment_terminal``

https://github.com/OCA/pos/blob/8.0/hw_telium_payment_terminal/__openerp__.py
or with ``pywebdriver`` librairy https://github.com/akretion/pywebdriver/.

What are you using ?

**Comment by cvinh** [comment]
We were using hw_telium_payment_terminal on the posbox wired with rs232 ingenico terminals.
Now the ingenico devices are wireless (wifi or 4G) and I was wondering how to make them work with the iotbox... ingenico guys say that they can accept the communication with wifi or even bluetooth...
