### ISSUE TITLE
POS margin odoo 14

### ISSUE THREAD

**Issue by ahmed22s885111qq** [OCA/pos#784]
How can i hide or delete the percentage of margin from the POS window?
https://lionheart-1992.nimbusweb.me/s/share/6799869/vuucmgvwt9c250x0uv0z

i had  Display Margin option but the total margin rate remains .
https://lionheart-1992.nimbusweb.me/s/share/6799867/98lf2ghhbsdggtyqvf7b

**Comment by legalsylvain** [comment]
Just tested on runboat : bug confirmed. Thanks for reporting.

Could you propose a patch to fix that ? 


@dsolanki-initos, @fshah-initos, @ivantodorovich 

Here is the commit where some ``t-if`` disappeared : https://github.com/OCA/pos/pull/663/commits/a592edf415b72bc7816936e9446b722d491adaff#diff-d3eb5be21bd164ab0ceac3fef1c9eb23189d048cea63ecd483780656da29127c

regards.

**Comment by antoniocanovas** [comment]
We are working on it.
There is other issue when product cost is = 0, margin is not calculated.

**Comment by ahmed22s885111qq** [comment]
Hi everyone

is there any solution for this bug ?

**Comment by cvinh** [comment]
Fix here https://github.com/OCA/pos/pull/820
