### ISSUE TITLE
Request update to V15 for  pos_payment_change. 

### ISSUE THREAD

**Issue by artdijk** [OCA/pos#797]
We hope the update from V14 to V15 is a small step for you the experts.
Is there a planning for this module?
Thank you

**Comment by legalsylvain** [comment]
Hi. I didn't understood your question. Is it a request for quotation ?

**Comment by artdijk** [comment]
Hi Sylvain,

Thank you for your quick response.

No it is not a request for a quotation.

We are hoping for a V15 version of the Pos module that we can use for free. We are a small company and custom made for us it too expensive.

Are you planning to update to V15?

Thank you,

Arthur

 

Van: Sylvain LE GAL ***@***.***> 
Verzonden: vrijdag 3 juni 2022 15:20
Aan: OCA/pos ***@***.***>
CC: artdijk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [OCA/pos] Request update to V15 for pos_payment_change. (Issue #797)

 

Hi. I didn't understood your question. Is it a request for quotation ?

**Comment by legalsylvain** [comment]
No planned to migrate this module.
You can follow the migration to the V15 in the dedicated issue.
https://github.com/OCA/pos/issues/719
Kind regards.
