### ISSUE TITLE
[13.0][pos_order_mgmt] Wrong format date and time in pos receipt when reprinting

### ISSUE THREAD

**Issue by javierjcf** [OCA/pos#839]
## pos_order_mgmt
When I do a ticket I get the date and hour in my timezone. When I reprint that order is in american format and in UTC.

When ticket is printed firs time, odoo computes a field called formatted_validation_date with new Date(), whitch includes timezone.
When reprint, we get order_data.date_order un UTC, so when in the module you do:

```js
 // Get Date
            if (["print"].indexOf(action) !== -1) {
                order.formatted_validation_date = moment(order_data.date_order).format(
                    "YYYY-MM-DD HH:mm:ss"
                );
```

The date does not respect original format, in my case dd/MM/YYYY, and is not converted from UTC to user timezone.

Somethgn like this solves tge issue I think:

```js
    var local_date_hour = new Date(order_data.date_order + ' UTC').toISOString()
    order.formatted_validation_date = moment(local_date_hour).format(
        "DD/MM/YYYY HH:mm:ss"
    );
```

When the module calls the server, doing self.date_order I get UTC date, so in javascript is in UTC too. It should be converted to get the same date and same format than original receipt

**Comment by chienandalu** [comment]
Hi, @javierjcf Can you make the PR?

**Comment by javierjcf** [comment]
Hi @chienandalu.

New PR: #850
