### ISSUE TITLE
[14] pos_receipt_hide_price    is useless, it hides the price but shows vat

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/pos#868]
The aim of the module is to hide the price when me give a present. If you hide the price but you dont hide the 21% vat and the amount of vat, the person who recives the gift , can gues the value of the present

## Module
[14] pos_receipt_hide_price

## Describe the bug
it shows vat

## To Reproduce
14

1. install module
2. sell in pos
3. print the tiket

**Expected behavior**
no price no vat

**Comment by legalsylvain** [comment]
Makes sense. Could you provide a patch ? 

thanks !

**Comment by fgarcia-humanoide** [comment]
I am a functional consultant, and have no cualification in programing. Will ask the user if he wants to finance the patch.

Thanks
