### ISSUE TITLE
Manage container on Odoo version 16 ?

### ISSUE THREAD

**Issue by YannickLevadoux** [OCA/pos#874]
Hello 

I was wondering if it is possible to manage container for our shop with Odoo version 16 ?

We are using odoo 12 provided by a (expensive) third party editor, and watching if switching to the community version, the last one, v16, could be interesting. 
The point is we are selling bulk products. Customer comes with their own containers on which we have put a barcode.
Scanning this barcode before putting the filled container on the scale allow us to remove the weight of the container and to have only the weight of the bulk product. 
Our current Odoo edition manage this somehow. 

So I'm asking the community if there is a way to do the same thing with the last Odoo community version.

Thanks

**Comment by flotho** [comment]
Hi, thanks for this question.
I'm not sure to really understand your need, actuallly I meant that what you described looks like a real standard opensource edition workflow with scale and barcoding product.
IMHO it should be an easy setup but maybe @legalsylvain could make me wrong and share with you his experince regarding such process.

**Comment by YannickLevadoux** [comment]
Thanks for this reply.
Let me first try to make my need crystal clear :) 

The point is we are selling bulk products. Customer comes with their own containers on which we have put a barcode.
Those barcodes are labelled by us, with a specific barcodes nomenclature in Odoo.
So when we scan a 'new' barcode inside the PoS, odoo offers you to create a new container, you put it on the scale and we register this container in odoo with its weight.
After that when the customer has filled his container with some stuff and comes to the PoS, we scan the barcode, we then select the product inside, and we put container on the scale. In the software, we can see a total weight (product + container) and the product's weight (only the bulk product). This last weight is then used to calculate the price.

So yes, it's look like standard, not complicated stuff, but I do not manage to do it and maybe it's just a matter of configuration.
If there is any documentation I can refer to, I'll be glad to read it
Thanks !

**Comment by flotho** [comment]
> Thanks for this reply. Let me first try to make my need crystal clear :)
> 
> The point is we are selling bulk products. Customer comes with their own containers on which we have put a barcode. Those barcodes are labelled by us, with a specific barcodes nomenclature in Odoo. So when we scan a 'new' barcode inside the PoS, odoo offers you to create a new container, 

Could you describe the need of creating a new container and what is a container for you? Is it your human definition or a specific model from Odoo, if yes could you share it with us

> you put it on the scale and we register this container in odoo with its weight. After that when the customer has filled his container with some stuff and comes to the PoS, we scan the barcode, we then select the product inside, and we put container on the scale. In the software, we can see a total weight (product + container) and the product's weight (only the bulk product). This last weight is then used to calculate the price.
> 
Hum... I think I can understand better. 
Now can I ask you some questions : 
* does the barcode representing a person, a container or a product
* does the customer can fill the container by anything 

> So yes, it's look like standard, not complicated stuff, but I do not manage to do it and maybe it's just a matter of configuration. If there is any documentation I can refer to, I'll be glad to read it Thanks !

What can be done easily (without code) if the container is supposed to be filled only by the same product (I know it's the easy part) : 
* create a product with barcode that need scale : your container for this specific product
* when the customer come to the desk, use the scale and record the weight with minus 
* when he came back, put the container on the weight with the proper product and everything will be fine 

BUT of course I suppose that people can fill their container by anything. 
I think that if you ask people what product they will fill their container with you'll be able to design a specific nomenclature of product that will return you the equivalent price of the product as a refund value eand you'll probably be able to fallback on the first case.

I'm not sure that everything could be dealed without code and only by configuration but I think that with a proper product / barcode setup and a slightly different process you should achieve your goals.
Feel free to explore all the version of this repo you'll find more ideas and checkout the https://github.com/grap managed by @legalsylvain it will give you more ideas.
Hope it could help anyway

**Comment by YannickLevadoux** [comment]
Thank you for complete answer !

The need of creating a new container is related to a customer, who come with his own jar. 
He then can fill it with any bulk product we offer in the shop.
So for me, a container is both my human definition and something specific in Odoo.
In Odoo, all containers have their own weight because they are all different

So a barcode in my previous post, represents container. There is a specific barcode nomenclature for this usage.

Let me add some screenshot to show you what it look like in Odoo (sorry it's in french :) )

From the PoS : 
![Screenshot from 2022-10-30 18-48-06](https://user-images.githubusercontent.com/112521563/198893426-b38916ba-edda-4d7c-8526-8ade0cb3cf41.png)
Container list:
![Screenshot from 2022-10-30 18-48-21](https://user-images.githubusercontent.com/112521563/198893427-358f5482-6e27-4468-990b-3e44060cdb9f.png)
Usage of a container:
![Screenshot from 2022-10-30 18-49-04](https://user-images.githubusercontent.com/112521563/198893430-bbb1025b-f5fa-4a93-85a0-9a3f6c812113.png)

I understand what you said about changing the process in the shop, but I don't thing it will work because every container is different. And if I understand well, this make the usage of container difficult for both the customer and us. 

The solution is probably code and I've understood it's not available natively in Odoo 16. 
I've found a pos_container module on [another git repo](https://git.myceliandre.fr/Myceliandre/pos/src/branch/12.0-vracoop-pos) but it actually does not work on Odoo 16, and on Odoo 12, it does not work either (I've opened an issue for that on the git repo) we will see :)

So I will take a look https://github.com/grap. It looks interesting ! 
And maybe @legalsylvain has better idea ?

**Comment by kimasplund** [comment]
just a Q or observation. 
Does it not make more sense to weigh in and out if its trucks that come? unless it is very busy scale? just have them put barcode (or better yet QR code for visibility and ease) in the front window representing the customer and two cameras on each end. entry camera put in a table weight and exit camera other and they pay the difference just by the kg. no need to have a bunch of different container configurations stored. 
Or if you just weigh the container by it self? then i can understand this makes sense. you just weigh the empty container once and then charge difference in the future.

**Comment by YannickLevadoux** [comment]
The very first time we weigh the container it self, store the weigh in Odoo and put a bar code on it.
Then every time the customer comes back to buy whatever he needs, we weigh the all stuff and remove jar's weigh.

It's a very basic process but very efficient ! 
And also very practical. No need for specific process. Customer enter the shop and just pick whatever they need. 
The customer enjoy it because they reuse some jars and it help to reduce packaging / trash.

**Comment by khamoud1** [comment]
Yes, your request is easily done by assigning every barcode to a customer. For this customer, you can apply a special discount specific to them. Alternatively, every barcode can represent a product itself. In any case, it is not complicated and can be achieved with some tweaking

**Comment by YannickLevadoux** [comment]
I don't understand : Assigning a bare code to a customer may be possible somehow, but what about getting the weight of each of his containers ?
