### ISSUE TITLE
[8.0] If start with using product template in price-list rule it is not working

### ISSUE THREAD

**Issue by krupesh-weboffice** [OCA/pos#90]
Hello,
When I am using this module for pricelist it is not working. It is only working with the If we use only products or categories it works perfect , once we use product template in any of the rule all products after that rule( same or higher sequence) will have same price which is completely messing up the pricing . 

Module: pos_pricelist

@StefanRijnhart 
@antespi 
@pablocm-aserti 
@AdilHoumadi 
@JavierIniesta 
@pablocm-aserti

**Comment by legalsylvain** [comment]
Do you use pos_product_template too ? or only pos_pricelist ?
regards.

**Comment by krupesh-weboffice** [comment]
@legalsylvain  
No, I am only using pos_pricelist.

**Comment by rafaelbn** [comment]
There is a PR for solving this issue in https://github.com/OCA/pos/pull/100

**Comment by krupesh-weboffice** [comment]
@rafaelbn thanks for your reply. I will have a look to it and also I fixed that bug earlier by my self.

again thanks
