### ISSUE TITLE
why pos_product template module does not function?

### ISSUE THREAD

**Issue by omarfrikha** [OCA/pos#92]
the module pos_product_template in this linck https://github.com/OCA/pos/tree/9.0/pos_product_template isn't working in my server odoo is generate this problem:
D\xe9tails de l'erreur :
L'\xe9l\xe9ment '<xpath expr="//link[@id='pos-stylesheet']">' ne peut \xeatre localis\xe9 dans la vue parente

Contexte de l'erreur :
Vue `product_template index`
[view_id: 723, xml_id: product_template.index, model: n/a, parent_id: 633]
None" while parsing None:12, near
<data name="product_template index" inherit_id="point_of_sale.index">
    <xpath expr="//link[@id='pos-stylesheet']" position="after">
        <link rel="stylesheet" href="/product_template/static/src/css/ppt.css" id="pos_product_template-stylesheet"/>
    </xpath>
</data>

 i did know why, how resoudre this problems??

**Comment by legalsylvain** [comment]
Hi @omarfrikha, 
You're trying to use a non ported module. 'pos_product_template' only works for V8 serie for the time being. 
That's why the module is set as 'installable' : False.
https://github.com/OCA/pos/blob/9.0/pos_product_template/__openerp__.py#L78

Feel free to port this module and propose a PR.

kind regards.

**Comment by omarfrikha** [comment]
how to instaled in my base in odoo 9
??

2016-03-24 10:59 GMT+01:00 Sylvain LE GAL notifications@github.com:

**Comment by pedrobaeza** [comment]
@omarfrikha, Sylvain has already told you that it can't be installed. You have to migrate it, or pay someone to migrate it for you.

**Comment by omarfrikha** [comment]
how to migrate it to 9??

2016-03-24 13:12 GMT+01:00 Pedro M. Baeza notifications@github.com:

**Comment by pedrobaeza** [comment]
Changing what don't work, but if you make such question, for sure you need to train yourself a lot or choose the second option. There's a third option, that is wait for someone that generously makes this migration for you, but there's no guarantee that this happens soon.

**Comment by omarfrikha** [comment]
can you help me with documentation of the method for migrate a  module??

**Comment by pedrobaeza** [comment]
Sorry, but this is out of the scope of this. There's no exact documentation for "migrating a module", because it depends on the data layout, the API changes..., and only experience makes this successful.

**Comment by omarfrikha** [comment]
there are another module in Odoo as module pos_template_product?.?? where
is?
