### ISSUE TITLE
Footer popup buttons pos_edit_order_line not translated

### ISSUE THREAD

**Issue by flachica** [OCA/pos#941]
Footer buttons of Edit order line (pos_edit_order_line) always appear in English

## Module
pos_edit_order_line

**Expected behavior**
String must be translated to system lang

**Comment by flachica** [comment]
Fixed in https://github.com/OCA/pos/pull/940

**Comment by chienandalu** [comment]
No need to open an issue if you already made a PR :slightly_smiling_face:
