### ISSUE TITLE
pos_payment_terminal on odoo 9.0

### ISSUE THREAD

**Issue by sydetion** [OCA/pos#95]
Error during installation:
ParseError: "Invalid view definition

Fehlerdetails:
Element '<xpath expr="//link[@id='pos-stylesheet']">' kann nicht in der \xfcbergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `pos_payment_terminal index`
[view_id: 849, xml_id: k. A., model: k. A., parent_id: 632]
None" while parsing None:11, near
<data name="pos_payment_terminal index" inherit_id="point_of_sale.index">
    <xpath expr="//link[@id='pos-stylesheet']" position="after">
        <link rel="stylesheet" href="/pos_payment_terminal/static/src/css/pos_payment_terminal.css" id="pos_payment_terminal-stylesheet"/>
    </xpath>
</data>

**Comment by legalsylvain** [comment]
Hi @sydetion, pos_payment_terminal doesn't work in V9 serie ('installable' = False in the manifest), you can try to port it or pay someone to do it.
kind regards.

**Comment by sydetion** [comment]
@legalsylvain I got that it is not already ported but I don't find any guidelines what have changed between 8.0 and 9.0 otherwise I'd like to port this addon and contribute it to the project
