### ISSUE TITLE
12.0-16.0 handle product.packaging in Odoo PoS

### ISSUE THREAD

**Issue by legalsylvain** [OCA/pos#963]
# Quick Setting

* Install PoS
* Go to Inventory > Configuration > settings and enable "_​Product Packagings_"
* Create a product like this

![image](https://user-images.githubusercontent.com/3407482/230575329-2db3d2c3-eca6-4b01-bef6-d6185190c9fb.png)

* Create a Packaging like this

![image](https://user-images.githubusercontent.com/3407482/230575659-995b6048-151b-4bd1-9251-46d73ca27f8d.png)

* Open your Point of Sale

- Scan the product. (2341321000002). it works (adding 1x Bottle)
- Scan the package (3356997201003). It doesn't work. 

**Expected behaviour** : adding 6 x bottle in the current PoS Order.

How do you handle that case ?

Thanks ! 

CC : @remytms , @quentinDupont , @ivantodorovich, @PierrickBrun

**Comment by hparfr** [comment]
I doubt it is implemented.

The easiest way to solve this, is to use  a different product for the pack. And do not use packaging for that.

**Comment by cvinh** [comment]
Hello we use BoM with kit option... beers also ;-)

**Comment by legalsylvain** [comment]
>  And do not use packaging for that.

Thanks @hparfr, for your answer. But so, in which case product.packaging is usefull ? 
I mean, I don't understand why a barcode field is present in this model, if it is useless.

**Comment by legalsylvain** [comment]
> Hello we use BoM with kit option... beers also ;-)

thanks @cvinh. indeed, that's the alternative way. 

**Cons :** 
- I have to fully configure another product
- I have to configure a BoM
- It duplicates product entries in my reportings. It is so complicated to know what is the "top product" for exemple.

**Pro :** 
- I can set a different sale price for the pack. (but for the time being, I don't need it).

**Question :** 
- what is the "kit option" ?
- in the use case where you buy only pack of 6, and you sell pack of 6 or single bottles, how do you unpack automatically ? (to avoid to have negative quantity on the "bottle single" product ?

**Comment by cvinh** [comment]
> * what is the "kit option" ?

Bom Type = kit
This is for not doing manufacturing order but taking the components out of the stock

**Comment by cvinh** [comment]
> * in the use case where you buy only pack of 6, and you sell pack of 6 or single bottles, how do you unpack automatically ? (to avoid to have negative quantity on the "bottle single" product ?

For Hinano beer that we love to drink in Tahiti, we have cans that can be sold individually or by pack of 6... but we buy them from supplier by pack of 24 (6x4).
Master product is the can as unit, it's used as main product for stock inventory...  etc (Purchase unit is 'pack of 24')
Another product is 'pack of 6 cans' that have a kit bom (6 units for a pack)
It works very well

**Comment by legalsylvain** [comment]
Thanks !

**Comment by didierdonze** [comment]
We will have the same requirement for a new customer selling beverages and might develop a module for it. Stay tuned! Target: V16

**Comment by legalsylvain** [comment]
Thanks @didierdonze for the information. Please ping me when you developped the module.
If I can avoid to configure mrp bom just for packaging, and reuse the ``product.packaging`` that seems to be simple, it's great.
