### ISSUE TITLE
Tare barcode not recognized in the scaling screen

### ISSUE THREAD

**Issue by sanrav** [OCA/pos#984]
The barcode of the tare is not properly recognized when I scan it in the scaling screen. 

## Module
pos_tare

## Describe the bug
When I scan the barcode of the tare, ODOO comes back to the previous screen (order screen, list of products) and doesn't add the product to the order. Moreover, the weight of the barcode is not properly read because ODOO indicates the reference of the barcode as weight instead of extracting the weight from the reference of the barcode. 

## To Reproduce
**V12**:

1. Configure the POS with these values : field iface_tare_method = both, iface_gross_weight_method = scale, is_posbox = true, barcode_scanner = true, barcode_nomenclature_id = Default nomenclature, iface_electronic_scale = true, iface_scan_via_proxy = true
2. Configure a product with these values : type= product, uom_id = kg, available_in_pos = true, to_weight = true
3. Open a POS session and choose the product
4. The scaling screen automatically appears => scale the gross weight then scan the tare barcode => ODOO comes back automatically to the order screen. If you select again the same product, here is the screen that appears (we can see the tare read by ODOO) : 

![image](https://user-images.githubusercontent.com/39826575/233984561-05b3875c-c8bc-4e6b-add8-2b666d276e37.png)

Here is my tare barcode

![image](https://user-images.githubusercontent.com/39826575/233985070-f408ef69-5934-4a75-9c11-61a1dbedb481.png)

This barcode is properly read and understood by ODOO when I scan it from the order screen.

**Expected behavior**
I'm expecting that ODOO can read properly the weight of the barcode when I scan it in the scaling screen and put it into the tare field in this screen. Then, when I come back to the order screen, my product is added with the gross weight, the tare and the net weight.

**Comment by legalsylvain** [comment]
@Fkawala : as you implemented the barcode feature.

**Comment by Fkawala** [comment]
I'll need a few days before looking into it.
