### ISSUE TITLE
[RFC] Postal Code MK Estrategy

### ISSUE THREAD

**Issue by fcvalgar** [OCA/pos#988]
**Is your feature request related to a problem?**
It would be interesting to have statistics of point-of-sale shoppers by zip code. We usually see this type of data collection that will be analyzed for future commercial openings.

**Describe the solution you'd like**
A module with a field would be included in the order confirmation, I attach a screenshot.
The data must be displayed in the backend.

![Odoo-POS-postal-code](https://user-images.githubusercontent.com/17847432/234248621-46f1ce89-5163-45da-b0f3-f23ecea92370.png)

@moduon

Thanks for your point of view.

CC : @OCA/pos-maintainers

**Comment by ferdymercury** [comment]
Very good idea. We also do this analysis off-line because Odoo misses such a strategy. It would be great if there could be not only a histogram-view, but also a map-view using openstreetmaps, such as: total of POS orders by zipcode as circle

![image](https://github.com/OCA/pos/assets/10653970/cd8d6999-4be7-4ebe-8e91-2de9433f4842)

**Comment by ferdymercury** [comment]
Related PR:
https://github.com/odoo/odoo/pull/121594

**Comment by ferdymercury** [comment]
Sale reports can be now grouped by customer ZIP for odoo 16.4, see https://github.com/odoo/odoo/pull/123146

It would still be nice to have a geomap view oca plugin instead of a simple table.

**Comment by fcvalgar** [comment]
It is a good improvement but we are looking not to store customer data. We want geographic statistic of pos customers.

Thanks for the info @ferdymercury

**Comment by rafaelbn** [comment]
@fcvalgar https://github.com/OCA/pos/pull/1045
